### PR TITLE
Get rid of toast-column class

### PR DESCRIPTION
**Pull request by limonte**
Towards #2213

### CODE REVIEW

**Comment by YogliB** [comment]
This is breaking toast styles:
image

**Comment by limonte** [comment]
> This is breaking toast styles:
> image

@YogliB Please use

```js
Swal.fire({
  toast: true,
  title: '...'
})
```

instead of 

```js
Swal.fire({
  toast: true,
  html: '...'
})
```

**Comment by YogliB** [comment]
This is how I'm using it:
```javascript
	const Toast = Swal.mixin({
		toast: true,
		position: 'top-start',
		showConfirmButton: false,
		timer: 3000,
		timerProgressBar: true,
		didOpen: (toast) => {
			toast.addEventListener('mouseenter', Swal.stopTimer);
			toast.addEventListener('mouseleave', Swal.resumeTimer);
		},
	});

       const alertSuccess = (text: string, options?: SweetAlertOptions) => {
		return this.Toast.fire({ icon: 'success', text, ...(options || {}) });
	}

        alertSuccess('Great Success!');
```

**Comment by limonte** [comment]
```diff
- 		return Toast.fire({ icon: 'success', text, ...(options || {}) });
+		return Toast.fire({ icon: 'success', title: text, ...(options || {}) });
```

**Pull request merged**
