### PR TITLE
chore: update sass to 1.22.1

### LINKED ISSUE #1636: An in-range update of sass is breaking the build 🚨
## The devDependency [sass](https://github.com/sass/dart-sass) was updated from `1.22.0` to `1.22.1`.

🚨 [View failing branch](https://github.com/sweetalert2/sweetalert2/compare/master...sweetalert2:greenkeeper%2Fsass-1.22.1).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

sass is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **continuous-integration/appveyor/branch:** AppVeyor build failed ([Details](https://ci.appveyor.com/project/limonte/sweetalert2/builds/25572160)).
</details>

---

<details>
<summary>Release Notes for Dart Sass 1.22.1</summary>

<p>To install Dart Sass 1.22.1, download one of the packages above and <a href="https://katiek2.github.io/path-doc/" rel="nofollow">add it to your PATH</a>, or see <a href="https://sass-lang.com/install" rel="nofollow">the Sass website</a> for full installation instructions.</p>
<h2>Changes</h2>
<h3>JavaScript API</h3>
<ul>
<li>Expand the dependency on <code>chokidar</code> to allow 3.x.</li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/sass/dart-sass/blob/master/CHANGELOG.md#1221">full changelog</a> for changes in earlier releases.</p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by gverni**
Upgrade sass to version 1.22.1

Fix #1636

### CODE REVIEW

**Comment by gverni** [comment]
@limonte I think the issue with `continuous-integration/appveyor/branch` is completely unrelated. All the other checks passed. I also tried that locally with no issue (tested on macOS). Is it a false alarm?

**Comment by limonte** [comment]
> Is it a false alarm?

so it seems

**Comment by gverni** [comment]
Thanks @limonte! Are you ok for me to merge this? Or you want to take more time to look into that?

**Pull request merged**
