### PR TITLE
Split SCSS into smaller pieces for easier theming

### PR DESCRIPTION
**Pull request by cichacz**
I made this change because current sass structure doesn't allow for easy theming.
For example, when using Nebular or any other themeable UI there's usually a way to style component using defined themes.

In Nebular one would do something like this:
```scss
@include nb-install() {
    // component-related theme overrides
    $swal2-black: nb-theme(text-basic-color);
    ...
}
```

Currently importing the `sweetalert2.scss` inside `nb-install` function would result in errors due to existing `@keyframes` rules and `body {...}` selectors (because Nebular adds `body` selector by itself with it's own theme class).

So doing this would produce an error:
```scss
@include nb-install() {
    @import '~sweetalert2/src/sweetalert2';
}
```

After changes it's possible to import breaking rules separately which allows for proper theming:
```scss
@include nb-install() {
    $swal2-background: nb-theme(background-basic-color-3);
    $swal2-black: nb-theme(text-basic-color);

    @import '~sweetalert2/src/scss/theming';

    @include sweetalert2-body();
    @include sweetalert2-toasts-body();
}

@import '~sweetalert2/src/scss/polyfills';
@import '~sweetalert2/src/scss/animations';
```

### CODE REVIEW

**Comment by limonte** [comment]
Thank you @cichacz for this PR!

All is well except the stylelint is reporting some errors, running `yarn run lint` will show them.

Could you please fix them? Thanks!

**Comment by limonte** [comment]
Thank you @cichacz for this PR!

All is well except the stylelint is reporting some errors, running `yarn run lint` will show them.

Could you please fix them? Thanks!

**Comment by cichacz** [comment]
Thank you @limonte for the heads up!
My linter was set to something a bit different :)
Should be better now.

**Comment by limonte** [comment]
@cichacz FYI, I moved `variables.scss` back in #1739 because themes depend on that: https://github.com/sweetalert2/sweetalert2-themes/blob/master/dark/dark.scss#L1

**Comment by cichacz** [comment]
Ah, yea probably moving existing `scss` files wasn't the best move...
@limonte Not sure if anybody would import for example `toasts.scss` separately, if yes, then maybe it will be safer to put old files in old place?

**Pull request merged**
