### PR TITLE
 Fix backdrop animation by adding .swal2-shown class asynchronous

### LINKED ISSUE #650: CSS Animations not working on SWAL2 elements
If you increase the transition background-color duration it doesn't work as expected. So for example, if increase the transition duration to 2s, on open it doesn't transition the 2s duration and on exit the container gets removed before the transition finishes.

Here's a jsfiddle example:
https://jsfiddle.net/treece/r2n743e7/

### PR DESCRIPTION
**Pull request by limonte**
Fixes #650

### CODE REVIEW

**Comment by limonte** [comment]
This PR fixes the backdrop animation for single modal, but unfortunately, there's a regression for chaining modals - the backdrop is flickering.

**Comment by acupajoe** [comment]
@limonte A solution to this would be to separate the backdrop element from the swal2 container. This way a backdrop could remain in the DOM while in a chaining modal state. 

If you agree that this is a viable option, I'm happy to write the code for it!

**Comment by limonte** [comment]
Go ahead @acupajoe :rocket: , separating the backdrop element from the swal2 container might be the proper way to fix the issue.

**Comment by acupajoe** [comment]
@limonte I think that will do it!

**Comment by limonte** [comment]
Many thanks @acupajoe! The fix looks exactly like we were planning. The only one thing I'm not 100% happy is related to UX. There's the noticeable delay between closing the modal and closing the backdrop.

As a user, I want to be able to work with my document asap after I clicked a button in the modal window.

Give me 2-3 days to review this PR, I think I have a simple solution in my mind, but I'm can't visualize it completely :) 

Thanks again and have a great working week!

**Pull request closed without merging**
