### PR TITLE
Wrapper for Vue.js

### PR DESCRIPTION
**Pull request by avil13**
A convenient wrapper for sweetalert2.

### CODE REVIEW

**Comment by limonte** [comment]
Thanks for the PR @avil13!

For people who are not so familiar with Vue.js, could you please explain what's the difference between your repo and https://github.com/lishengzxc/vue-sweetalert?

**Comment by avil13** [comment]
Hi.
My version connects your library more correctly.
What gives additional features in the API Vue.

**Comment by limonte** [comment]
Could you please elaborate "more correctly" with an example?

**Comment by avil13** [comment]
I apologize.

In fact, the code that would be different, not so much.
And it is 80% similar.

The main difference is that my version is a full Vue wrapper.
Basically, within Vue applications, you need to use methods in the context of the object.
Which, moreover, it is better not to have the right to change.

Example:

```javascript
export default {
    methods: {
        showAlert(){
            // Use SweetAlret2
            this.$swal('Hello world!');
        }
    }
}
```

But sometimes you need to have access to this method through a wrapper from outside.

```javascript
Vue.swal('Hello world!');
```

This difference is really minimal.
But it conforms to the rules for creating plug-ins for Vue.

In any case, it's up to you.
I just wanted to share the opportunity to do this.

Thank you.

**Comment by limonte** [comment]
Thanks for the explanation, now I see the difference :+1: 

Would you like to transfer your repository to the https://github.com/sweetalert2 organization and become a member of it?

By doing so, we can completely replace https://github.com/lishengzxc/vue-sweetalert with your project :rocket: 

What do you think?

**Comment by avil13** [comment]
Thanks for the suggestion.
Only I do not know what I should do.

**Comment by limonte** [comment]
I just added you to the https://github.com/sweetalert2 organization :+1: 

Now you can transfer the repo to it https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by limonte** [comment]
Perfect! I pinned your project to be visible here: https://github.com/sweetalert2

**Comment by limonte** [comment]
Final steps before merging:

 - update the url of your project
 - remove the lishengzxc/vue-sweetalert from the list

Many thanks!! :rocket: :rocket: :rocket:

**Comment by avil13** [comment]
Thank you.

**Comment by zenflow** [comment]
@limonte I think we should allow more time for discussion before we make an integration package officially endorsed & maintained. I have some skepticism about whether this package is helpful. See https://github.com/sweetalert2/vue-sweetalert2/issues/8, especially the last paragraph. Sorry..

**Comment by limonte** [comment]
@zenflow yup, seems that I was rushing without strong reasons to rush. Apologies to everyone.

It seems that @samturrell is doing Vue.js, Sam what is your opinion on adding this wrapper?

**Comment by samturrell** [comment]
I would agree that it's probably not the most necessary integration, however I do know that developers WILL try and find a package for it. And in that respect it's probably better to have it under the organisation umbrella so that there are a range of maintainers of the "official" wrapper for the future.

**Comment by toverux** [comment]
The same goes for Angular. People try to find an ng/ngx- prefixed library, and I can't even count those libraries today, everyone rolling its own, adding hyphens randomly in the packages' names to not conflict with the existing ones.
But most of them are only proposing a tiny JavaScript wrapper around SweetAlert (Classic or v2). This has no other effect than making SweetAlert2 complicated to update, can make auto-completion less powerful, some packages are even bundled with their own, oudated version of SA's dist files.
Some people did it for Angular to workaround the lack of typings, a problem that I solved first by adding a .d.ts on this repo, before creating my own library (that I would _not_ recommend if you only have 1 or 2 alerts to show). 
The main real effect of this type of integrations is that it just increases the final bundle size, makes everything more complicated and generates confusion and technical debt.

**Comment by limonte** [comment]
Thanks everyone for expressing your opinions and arguments. The repository was moved back to @avil13 but it will be listed in the [Related community projects](https://github.com/sweetalert2/sweetalert2#related-community-projects) section of README.

**Pull request merged**
