### PR TITLE
Remove withNoNewKeyword enhancer

### LINKED ISSUE #1368: Drop withNoNewKeyword in coming major release
The coming major release gives us the opportunity to drop this complexity and source of issue #1281 (so users can import uncompiled code from the `src/` directory again).

This would mean a breaking change as users would need to change their usage from `Swal({...options})` to `new Swal({...options})`, or if nothing is done with the result, and the [eslint no-new rule](https://eslint.org/docs/rules/no-new) is in effect, `Swal.fire({...options})`. I think for the sake of simplicity it might be best to only use the latter `Swal.fire()` in documentation, tests, issue descriptions, etc.

### PR DESCRIPTION
**Pull request by limonte**
Closes #1368

From now on the recommended way to use SweetAlert2 is:

```js
Swal.fire({...options})
```

### CODE REVIEW

**Comment by limonte** [comment]
@zenflow would you have time to take a look at this PR? 

Also, do I understand correctly that we don't need `withGlobalDefaults` as well?

**Comment by zenflow** [comment]
> would you have time to take a look at this PR?

Sure I'll have a look later today

> Also, do I understand correctly that we don't need withGlobalDefaults as well?

Correct

**Comment by limonte** [comment]
The bundle is 72B smaller now

In total, we'll make it 1KB smaller than the prev major  🎉 

@zenflow I'll merge this PR and continue with other tasks for the next major, feel free to give any feedback on this PR later.

**Comment by limonte** [comment]
:tada: This has been shipped in version 8.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/sweetalert2)
- [GitHub release](https://github.com/sweetalert2/sweetalert2/releases/tag/v8.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Pull request merged**
