### PR TITLE
Export input, grow and position options types

### PR DESCRIPTION
**Pull request by oliveiraeloi**
Export option types for better TS integration when there's a wrapper function for creating alerts.

e.g.:
import { SweetAlertPositionOption }  from 'sweetalert2';

function showToast(title: string, icon: SweetAlertIcon, position: SweetAlertPositionOption = 'center') {
  return Swal.fire({
    // ...
    position
  });
}

### CODE REVIEW

**Comment by toverux** [comment]
:+1: but I'd remove the "Option" suffixes. At least to stay consistent with the other types.
In the meantime or in the case this doesn't get merged, you may use `SweetAlertOptions['input']` etc. This TypeScript notation, as a type, returns the type of the property. [See this](https://github.com/sweetalert2/ngx-sweetalert2/blob/master/projects/ngx-sweetalert2/src/lib/swal.component.ts#L36).

**Comment by oliveiraeloi** [comment]
> +1 but I'd remove the "Option" suffixes. At least to stay consistent with the other types.
> In the meantime or in the case this doesn't get merged, you may use `SweetAlertOptions['input']` etc. This TypeScript notation, as a type, returns the type of the property. [See this](https://github.com/sweetalert2/ngx-sweetalert2/blob/master/projects/ngx-sweetalert2/src/lib/swal.component.ts#L36).

:+1: Removed suffix from PR to maintain consistency and moved types closer to SweetAlertIcon.

Currently I'm using a custom type that overlaps with Options definition to avoid index accessors, but thanks for the advice :smile:

**Comment by oliveiraeloi** [comment]
@limonte @toverux it's a pleasure to help and thank you for this great lib :smile:

**Pull request merged**
