### PR TITLE
Unset props after closing a popup so GC will dispose them

### LINKED ISSUE #1569: Memory management: references not detached
## Context

I am using swal2 in a heavy SPA that uses VueJs. I am currently busting all of the potential memory leakages in the application, and I believe I've found a potential threat coming from sweetalert2.  

## Current behavior

This problem occurs when you fire an alert using either a `preConfirm` or by just attaching a function through `.then()`, like so:

```
var baz = 4;
Swal.fire({
  title: 'Test',
  preConfirm: () => this.foo(baz)
}).then((d) => {
  if (d.value) {
    this.bar(baz)
  }
})
```

It is important to note that this `fire` method has been called inside a **vuejs** component, therefore the `this` context of both `foo` and `bar` includes a whole bunch of data/properties/methods that may consumes a lot of memory.

If this swal modal is fired and the user cancel it (e.g. by clicking outside), the swal closes itself and everything works like a charm, except when you move out of the current `vuejs` component, and take a quick look at a Chrome heap snapshot. Here is what I see :

image

We can clearly see that a `WeakMap` inside sweetalert is retaining a Promise (I'm using bluebird promises btw, but it also happens without bluebird).
This promise seems to have all my `vuejs` component attached as its context, preventing the GC from collecting the memory.

It is **not** an actual memory leak because the memory does not stack. It's just an annoying reference that prevent the GC from collecting the underlying context.

## Proposed solution

When going deeper using the debugger, I've identified the source of this behavior:

`privateMethods` and `privateProps`

- `privateProps.promise` is retaining a promise with my `vuejs` context.
- `privateMethods.swalPromiseResolve` seems to retain a `vuejs` context as well.
- `privateProps.innerParams` is retaining my `preConfirm` and therefore the `vuejs` context attached to the function.
- `privateProps.domCache` is retaining references a DetachedHtmlElement that can be seen in the heap snapshot. (less harmful but still)

### Code

Here is my proposed solution : https://github.com/jf-m/sweetalert2/commit/b2a77c6639c8d5f7b18bc24d5a58c85b41bd5218

I have not made any pull-request because I am not sure wether `removePopupAndResetState` is the right place to dispose of  `privateProps.innerParams`, `privateProps.domCache` and `privateMethods.swalPromiseResolve`...

However, I've tried my commit and the GC collects my vue components, is seems to work in my test case.

By the way, thank you for this amazing project, it's saving me a huge amount of time in all my projects ;) !

Cheers 🍺

### PR DESCRIPTION
**Pull request by limonte**
Fixes #1569

### CODE REVIEW

**Comment by limonte** [comment]
@jf-m could you please verify if this PR fixes your case?

PS. thank you for the detailed research of this issue!

**Comment by jf-m** [comment]
Hi @limonte ,

I've tried this PR, it solves the GC issue in my test case! 🍻 

However, there is two errors that appears now:

### First one
image
image

This one appear when stress-testing an alert. 
I assume `removeEventListener` just needs to be done only if `globalState` is not empty.


### Second one
It happened once only, and I could not reproduce it... Unfortunatly I cleared my chrome console afterwards so I did not take any screenshot.
The error was saying `Cannot read property 'onClose' of null` line 69 of `close.js`.
Meaning that  `innerParams` was null... But I counldnt reproduce it.
image
I probably just need a null check as well.

But the main issue is now solved !
Thank you guys for your reactivity.

Cheers

**Comment by limonte** [comment]
Good day @jf-m and thank you so much for the provided feedback!

> This one appear when stress-testing an alert.

I want to ask you to share some of your knowledge with us if that's fine :) Could you please briefly describe how are you doing the stress-testing? I would be happy to learn how to perform it and include it in CI build (to all builds or just to scheduled builds once a day).

**Comment by jf-m** [comment]
Hello @limonte ,

Of course :-)!
By 'stress-testing', I meant... Spaming the mouse click button like a headless chicken ! 🐔 🐔 
I spam the button that is supposed to fire the swal alert. That button is then hovered by the backdrop, so I suppose the click spam would just trigger the click event on the backdrop multiple times.
Here is how you could achieve this using QUnit:

```
QUnit.test('backdrop stress-test', (assert) => {
  const done = assert.async()

  SwalWithoutAnimation.fire('Backdrop click').then((result) => {
    assert.deepEqual(result, { dismiss: Swal.DismissReason.backdrop })
    done()
  })

  var t = $('.swal2-container');
  t.click()
  t.click()
})
```

**Comment by limonte** [comment]
@jf-m, unfortunately, I wasn't able to reproduce neither of the two issues you mentioned. It would be great if you can submit a PR with just a test which is failing so we can implement the proper fix for it.

**Pull request merged**
