### PR TITLE
Refactor/extract static methods

### PR DESCRIPTION
**Pull request by zenflow**
Towards #970

Moves all "static methods"  ("static" in the sense of methods of the "constructor", but excluding the ones depending on our "current instance" or `currentContext`) into modules in `src/staticMethods/`.

### CODE REVIEW

**Comment by limonte** [comment]
Love the commit history. This is the first time I'm thinking that by doing 'Squash and merge' I'm harming the commit history which in theory is a powerful tool but in practice quite often just a mess.

**Comment by limonte** [comment]
@zenflow what do you think about re-enabling the "Rebase and merge" option?

**Comment by zenflow** [comment]
@limonte I really just wrote the clean commit history for review purposes. I think that amount of granularity in the `master` commit log is too much. There I kinda just want to see a summary commit, like `refactor(modules): extract static methods from main module into src/staticMethods/`

**Comment by limonte** [comment]
Gotcha, done :+1:

**Comment by limonte** [comment]
Released in [v7.17.0](https://github.com/sweetalert2/sweetalert2/releases/tag/v7.17.0) :tada:

**Pull request merged**
