### PR TITLE
Fix/karma babel use es2015 preset

### PR DESCRIPTION
**Pull request by limonte**
Get rid of `promise-polyfill` devDependency, use `babel-polyfill` to fix currently failing build in AppVeyor (IE11):

```
  × inputValue as a Promise
	Died on test #1    at Anonymous function (webpack:///test/qunit/tests.js:858:0 <- test/qunit/tests.js:1:110983)
	   at n (webpack:///webpack/bootstrap:25:0 <- test/qunit/tests.js:1:98)
	   at Anonymous function (webpack:///webpack/bootstrap:68:0 <- test/qunit/tests.js:1:580)
	   at Global code (test/qunit/tests.js:1:2): 'Symbol' is undefined
	ReferenceError: 'Symbol' is undefined
	   at Anonymous function (webpack:///test/qunit/tests.js:865:2 <- test/qunit/tests.js:1:111442)
	   at runTest (node_modules/qunit/qunit/qunit.js:1478:6)
	   at run (node_modules/qunit/qunit/qunit.js:1464:6)
	   at Anonymous function (node_modules/qunit/qunit/qunit.js:1676:7)
	   at advance (node_modules/qunit/qunit/qunit.js:1116:6)
	   at begin (node_modules/qunit/qunit/qunit.js:3065:4)
	   at Anonymous function (node_modules/qunit/qunit/qunit.js:2063:6)
```

https://ci.appveyor.com/project/limonte/sweetalert2/build/272

---

Connected to #1025

### CODE REVIEW

**Comment by zenflow** [comment]
@limonte Actually we **should** be using `promise-polyfill` since we tell IE11 users that is the only polyfill they need to bring to their environment. The failure on AppVeyor indicates a portability issue:

> ReferenceError: 'Symbol' is undefined

There's a use of `Symbol` in our code (probably the transpiled code) which isn't supported in IE11

**Comment by limonte** [comment]
> Actually we should be using promise-polyfill since we tell IE11 users that is the only polyfill they need to bring to their environment.

Valid point, I'll revert `promise-polyfill` and try to figure out where does `Symbol` come from.

**Comment by zenflow** [comment]
@limonte on this subject, what do you think about just requiring IE11 users to have *all* the ES6 polyfills loaded? It would be great to use new language features that depend on globals, like `for .. of` (which uses `Symbol` under the hood and you can see it when transpiled) and `Array.prototype.includes` , and I don't think it's asking too much. Plus we're already requiring them to load the `Promise` polyfill, so the other polyfills could be included in the same bundle.

**Comment by limonte** [comment]
> Valid point, I'll revert promise-polyfill and try to figure out where does Symbol come from.

Done, the problem was in the newly added test which was using `for .. of` https://github.com/sweetalert2/sweetalert2/pull/1035

> on this subject, what do you think about just requiring IE11 users to have all the ES6 polyfills loaded? It would be great to use new language features that depend on globals, like for .. of (which uses Symbol under the hood and you can see it when transpiled) and Array.prototype.includes , and I don't think it's asking too much. Plus we're already requiring them to load the Promise polyfill, so the other polyfills could be included in the same bundle.

In the current terribly unstable front-end ecosystem, I think it's better to require as fewer dependencies and polyfills as possible. Asking for additional polyfills would be a breaking change for existing users and each breaking change hurts. Let's not hurt our users without strong reasons for that.

**Comment by limonte** [comment]
> Actually we should be using promise-polyfill since we tell IE11 users that is the only polyfill they need to bring to their environment.

There was a mistake in README as well, fixed: 
https://github.com/sweetalert2/sweetalert2/commit/31a236018611e1e537fd203029c0e797349e71cb

**Comment by zenflow** [comment]
@limonte 
> In the current terribly unstable front-end ecosystem, I think it's better to require as fewer dependencies and polyfills as possible. Asking for additional polyfills would be a breaking change for existing users and each breaking change hurts. Let's not hurt our users without strong reasons for that.

Our DX is a strong reason. And an es6 shim is the same number of dependencies as a es6-promise shim (one). You are correct to point out that it would be a breaking change though. We should do it in the next major. What do you think?

**Pull request merged**
