### PR TITLE
BREAKING CHANGE: inputValidator and preConfirm should always resolve

### PR DESCRIPTION
**Pull request by limonte**
This should be mentioned in docs, https://github.com/sweetalert2/sweetalert2.github.io/issues/57

### CODE REVIEW

**Comment by zenflow** [comment]
@limonte What's the reasoning for this? I put that test there intentionally to deal with unexpected errors in user-defined functions. If something goes wrong in their provided functions, I believe it should propagate the error, i.e. the call to `Swal.fire()` should reject, and the modal which is now in a potentially invalid state, should be cleaned up.

**Comment by limonte** [comment]
> What's the reasoning for this? I put that test there intentionally to deal with unexpected errors in user-defined functions. If something goes wrong in their provided functions, I believe it should propagate the error, i.e. the call to Swal.fire() should reject, and the modal which is now in a potentially invalid state, should be cleaned up.

I would prefer if SweetAlert2 would never reject, so as a developer I know that I should never bother myself with adding `catch` to `Swal.fire`.

If there's a possibility of unexpected exceptions in `preConfirm`, I believe this is the proper way to handle them:

```js
  preConfirm: () => {
    return new Promise(function () {
       throw new Error('boom')
    }).catch((error) => {
      Swal.showValidationMessage(error)
      return false
    })
  },
```

**Comment by limonte** [comment]
Thank you for your feedback @gverni! Would you mind to provide a code representation of this example:

> Currently for example, if the value of one of the innerParams is not correct, swal is just throwing a warning. IMHO it may be better if it actually rejects. Consider for example the use case where a developer is setting inputValue as return from another function he doesn't have a control on. In this case if this function is returning a not-expected type (i.e. a Date object) then the only thing that happen is a warning on console, and this is difficult to handle. If swal actually rejects in this case, then the developer could handle this specific case in a different way.

**Comment by gverni** [comment]
@limonte I put [here](https://glitch.com/edit/#!/secret-brake) an example of the use case I was talking about. I agree that it may not be that common, but it's just a way of explaining better (as you taught me, _code_ speaks a thousands words :-)). 

In this case we have a developer that want to redistribute SweetAlert2 _wrapped_ in his own class (see [SourAlert.js](https://glitch.com/edit/#!/secret-brake?path=SourAlert.js:1:0)). A 2nd developer is using SourAlert (wrongly) and is passing a `Date` object as `inputValue`.   

To make his product more robust, the developer of SourAlert needs to add a check on the `inputValue` passed from the 2nd developer, and this check is exactly the same that is done in Swal already (see [line 12](https://glitch.com/edit/#!/secret-brake?path=SourAlert.js:12:4)). 

If swal could provides a single function (`reject`??) where all these errors / warning are catched, then it will make SourAlert developer's life easier and his code less difficult to maintain. 

As I said, this is just a (probably very stupid) example of a scenario that can actually happen, especially if Swal is redistributed inside frameworks developed by 3rd party developers.  And sorry again for the off-topic example.

**Comment by limonte** [comment]
Thanks, @gverni for the detailed explanation and SourAlert :D

In SourAlert, a developer is modifying `inputValue` before calling `Swal`:

```js
if (!(typeof args.inputValue === 'string' || typeof args.inputValue === 'number')) {
  args.inputValue = args.inputValue.toString()
}
```

It would be irrelevant to do the same thing in `Swal.catch()`, so the SourAlert developer would still need to do the same thing even if we would be rejecting the promise in case of unexpected exceptions.

**Comment by limonte** [comment]
Because there are no strong objections, I'll merge this PR. @gverni please rebase #1379 on top of master and simplify it accordingly to this change. Thank you!

**Comment by limonte** [comment]
:tada: This has been shipped in version 8.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/sweetalert2)
- [GitHub release](https://github.com/sweetalert2/sweetalert2/releases/tag/v8.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Pull request merged**
