### PR TITLE
add ElectronAlert project

### PR DESCRIPTION
**Pull request by pjebs**

### CODE REVIEW

**Comment by limonte** [comment]
Thank you for the PR @pjebs but I have to reject it for now for these reasons:

- low quality, if it's not tested, it's broken (c)
- unused by community

Please come back after 100+ stars and tests :)

**Comment by pjebs** [comment]
It's a very thin wrapper around swal. It's just a swal alert inside a browser window. What tests can I possibly add?

Also any pointers how on how I can get more exposure in order to get more stars?

I was hoping adding it on this repo would do that.

**Comment by pjebs** [comment]
@limonte

**Pull request merged**
