### PR TITLE
Add STOP WAR message for Russians

### PR DESCRIPTION
**Pull request by limonte**
Adding the STOP WAR message to Russian users (`navigator.language === 'ru'`) visiting Russian sites (`.ru`, `.su`, `.рф`)

This message is targeted at people who are corrupted by propaganda, everybody else is already against war either silently or actively.

The point is to wrap the truth bomb into a patriotic title so they will actually click it and listen to the uncomfortable truth about the war from the people they love or respect.

There are for now 4 messages:
- From Arnorld Schwarzenegger, who is loved in Russia by all people including those brainwashed by propaganda.
- From one of the most famous Russian nationalist leaders, Dmitry Demushkin. He explains that this war has no sense and produces the exact opposite result of what it was intended to do.
- From Igor Girkin, who played a key role in the Annexation of Crimea. He explains that this war has failed already and all possible outcomes are bad for Russia.
- From Jussi Halla-aho, a Finnish politician who speaks Russian nicely and explains the price Russian citizens and their children will pay for this absurd war.

New messages might be added in the future.

Here's how the message will be shown:

CleanShot 2022-04-18 at 13 13 01@2x

---

PS. I don't have too much hope in this, there's a tiny chance that a brainwashed person will change their mind. But I have to do everything in my power to stop this war.

PS2. I am against politics in software, but this isn't politics anymore. This is a war, many people including women and children are dying every day and it has to be stopped.

### CODE REVIEW

**Comment by face-hh** [comment]
ok

**Comment by JuniorHerakuresu** [comment]
> 

ok.

**Comment by lofcz** [comment]
While the way this is implemented _is at least transparent_ (unlike some other packages obfuscating such efforts) I believe this should've been released as version 12 and clearly labeled as a breaking change.

**Comment by jtraulle** [comment]
*   [https://security.snyk.io/vuln/SNYK-JS-SWEETALERT2-2774674](https://security.snyk.io/vuln/SNYK-JS-SWEETALERT2-2774674)
*   https://cwe.mitre.org/data/definitions/438.html

**Comment by G1Vh** [comment]
Repeating https://github.com/RIAEvangelist/node-ipc story?

**Comment by maxnowack** [comment]
I understand your reasons and also support the ukraine, but please remove this behavior from sweetalert2 and let the owners of the website decide to implement it.
npm packages are not the right place for this.

**Comment by jtraulle** [comment]
I agree, you should revert this commit.

**Comment by CrazyHackGUT** [comment]
I was contacted by a friend who informed me about the presence of this banner on his site, and I tried to reproduce it for 10 hours with the English localization of the browser. 🤦 

Why was this done? Please, roll back. Or give site admins the choice to turn it off.

**Comment by limonte** [comment]
Hello, dear programmer from Russian Military Unit 25850. This was done because your country is killing civilians in Ukraine.

**Comment by lofcz** [comment]
@limonte while you don't owe your users a dime I would like to voice discontent with the way you are (not) responding to the community concerns regarding this PR

**Comment by CrazyHackGUT** [comment]
> Feel free to switch to another plugin to show modals.

Read my message carefully in next time, please. This shit is appeared on the website of my friend. And i spent 10 hours just because my OS and browser is using English language.

You just showed yourself from not the best side. You replied on my message just because I'm born and live now in Russia (in fucking Military Unit), who soldiers really killing civilians. But nothing replied to the messages directly above mine.
Keep developing your agenda. Good luck.

**Comment by nikitoSha** [comment]
Я поржал знатно, спасибо за хорошее настроение на вечер!
Дорогой хохлёнок. Твоя закладка, распиханная всюду по исходникам, вырезается за минуту.
Этот бой ты проиграл еще в тот момент, когда твоя голова родила такую слабенькую идею.
ШВАРЦНЕГГА, Подоляка... :D
Пойду почитаю сводки с фронта, как дурных нациков-бандэровцев выгоняют с русской земли.
Не позорься лучше и удали сам свои закладки. Удачи тебе, шварцнэгга))))))))

**Comment by long76** [comment]
u really? IT DOES NOT MAKE SENSE IN OPEN SOURCE!

**Comment by yarkovaleksei** [comment]
image

**Comment by sadikoff** [comment]
Hey,

I probably understand your position, but the site owner should decide by himself whether will he show some message or not, and that is a bad practice for open source to show messages you want on a resource that does not belong to you! Today you will show a peace message and tomorrow inject a crypto-miner in it!?

Cheers

**Comment by limonte** [comment]
> Hey,
> 
> I probably understand your position, but the site owner should decide by himself whether will he show some message or not, and that is a bad practice for open source to show messages you want on a resource that does not belong to you! Today you will show a peace message and tomorrow inject a crypto-miner in it!?
> 
> Cheers

Russian site-owners are scared and they love to pretend that nothing is happening, they would never protest against war.

**Comment by long76** [comment]
> > Hey,
> > I probably understand your position, but the site owner should decide by himself whether will he show some message or not, and that is a bad practice for open source to show messages you want on a resource that does not belong to you! Today you will show a peace message and tomorrow inject a crypto-miner in it!?
> > Cheers
> 
> The vast majority of russian site-owners are scared and they love to pretend that nothing is happening when the full-scale war is happening already for half a year. They would never protest against war which their country started because of the low moral standards.

But war is happening since 2014...

It's sounds like

> The vast majority of NATO-member site-owners are scared and they love to pretend that nothing is happening when the full-> scale war is happening already since 2014.(Before Ukraine, was Serbia, Iran, Irac) They would never protest against war which > their country started because of the low moral standards.

If you not from NATO forces u must add "STOP NATO!" for NATO-member country localizations.

If u will not do it u just do not like Russians like Germany do not like jews in XX century.(Although after ur many speech it does not require proof)

**Comment by nikitoSha** [comment]
Да это зомби, ничего не поймёт. Там каша в голове. 404.

**Comment by sadikoff** [comment]
> The vast majority of russian site-owners are scared and they love to pretend that nothing is happening when the full-scale war is happening already for half a year. They would never protest against war which their country started because of the low moral standards.

The Open Source is based on trust, if everyone begins to add anything to their Open Source projects what will be the weight of this trust? What about Russian-speaking people and countries which is not Russia? If you want to add something like this, ok no problem, but do it configurable. Keep the right of the site owner to choose the way he wants to proceed. THAT is the WAY of let say democracy. And what you have done? You are not better than people who accept war =) from my point of view. Just hiding under big words!

**Comment by limonte** [comment]
I love lessons about democracy and freedom from you guys 😆

**Comment by sadikoff** [comment]
Do you know me and where I leave? and what is my situation? Do not get this chat in person.

**Comment by sadikoff** [comment]
@limonte mark your comment as offtopic too, why just my comment? or you are untouchable in this discussion?

**Comment by xMaZax** [comment]
> I love lessons about democracy and freedom from people who lived their whole life under 1 dictator, please don't stop 😆

Do I remind you what wars your country participated in?

The Vietnam War (1955 – 1975)
The US Invasion of Grenada (1983)
The Invasion of Panama (1989 – 1990)
The Gulf War (1991) reports on this
Bombing of Yugoslavia (1999)
The war in Afghanistan (2001-2021)
The Iraq War (2003-2011)
Intervention in Libya (2011)
The intervention of the United States and its allies in Syria (since 2014)
Nuclear attack on Hiroshima (1945)

What a duplicitous opinion you have.
What do you say to that?)
I can list many more and many more

**Comment by luxicadi** [comment]
> u really? IT DOES NOT MAKE SENSE IN OPEN SOURCE!

Repository owners are allowed to do whatever they please with the repository they own.



> > I love lessons about democracy and freedom from people who lived their whole life under 1 dictator, please don't stop 😆
> 
> Do I remind you what wars your country participated in? Even Russia has not had so many conflicts in its entire history.
> 
> The Vietnam War (1955 – 1975) The US Invasion of Grenada (1983) The Invasion of Panama (1989 – 1990) The Gulf War (1991) Bombing of Yugoslavia (1999) The war in Afghanistan (2001-2021) The Iraq War (2003-2011) Intervention in Libya (2011) The intervention of the United States and its allies in Syria (since 2014) Nuclear attack on Hiroshima (1945)
> 
> What a duplicitous opinion you have. What do you say to that?) I can list many more and many more
> 
> When will people finally realize that changes like yours won't change anything and it just proves stupidity
> 
> You say that propaganda works for us. So ask yourself a similar question, maybe it works for you so much that you believe in fake news?

Every single country on earth is against you, unless it's a dictatorship and frequently breaks human rights (China) or is a Russian puppet state (Belarus). There's no "propaganda", Russian armies invaded Ukraine to expand Russia's power while killing innocent civilians in the process. Even your "reasoning" doesn't make sense. Stopping "nazis" by... killing innocent civilians and taunting them. How dare people place anti-war messages in their repositories! THE HORROR! We have to close a dialog box!!! 

### If you don't like the commit, make a fork, and change it.
Because that's what open-source software is about.

**Comment by luxicadi** [comment]
> If u will not do it u just do not like Russians like Germany do not like jews in XX century.(Although after ur many speech it does not require proof)

Oh please. Your country was an accomplice to the holocaust. Russians are not oppressed in any way, shape, or form. You people think you're entitled to everything, even an entire fucking country. You live under an oppressive dictatorship and you like it. The soviets were as bad as the nazis, they were just a bit more humane (but I definitely wouldn't call them humane) and better at covering their tracks.

**Comment by luxicadi** [comment]
> > The vast majority of russian site-owners are scared and they love to pretend that nothing is happening when the full-scale war is happening already for half a year. They would never protest against war which their country started because of the low moral standards.
> 
> The Open Source is based on trust, if everyone begins to add anything to their Open Source projects what will be the weight of this trust? What about Russian-speaking people and countries which is not Russia? If you want to add something like this, ok no problem, but do it configurable. Keep the right of the site owner to choose the way he wants to proceed. THAT is the WAY of let say democracy. And what you have done? You are not better than people who accept war =) from my point of view. Just hiding under big words!

Pretty sure the people that fall under that category either live in a Russian-controlled puppet state or are in a different country but still are citizens of Russia. Even if that's not the case, I think they can survive a little "stop war" dialog box, no?

**Comment by luxicadi** [comment]
> Я поржал знатно, спасибо за хорошее настроение на вечер! Дорогой хохлёнок. Твоя закладка, распиханная всюду по исходникам, вырезается за минуту. Этот бой ты проиграл еще в тот момент, когда твоя голова родила такую слабенькую идею. ШВАРЦНЕГГА, Подоляка... :D Пойду почитаю сводки с фронта, как дурных нациков-бандэровцев выгоняют с русской земли. Не позорься лучше и удали сам свои закладки. Удачи тебе, шварцнэгга))))))))

Please stop sending non-sense in the form of moon runes and/or spaghetti letters. Thanks.

**Comment by TchernyavskyDaniil** [comment]
Thank you! We have an excuse to get rid of this buggy library

**Review by slumericanB — COMMENTED** [review]
good

**Comment by WilliamStam** [comment]
im not russian, have no ties to russia and i most definitely dont agree with the war. but adding something like this in a rather well used library is really low (childish?). why not just create a plugin dedicated to adding this should the website owner decide to include it and putting a banner on the docs for it. 

i got here via:

```
# npm audit report

sweetalert2  >=11.4.9
sweetalert2 v11.4.9 and above contains hidden functionality - https://github.com/advisories/GHSA-qq6h-5g6j-q3cm
fix available via `npm audit fix --force`
Will install sweetalert2@11.4.8, which is a breaking change
```

and will be reverting because if any one in management sees a "hidden functionality" in any report theres gonna be hell to pay :( 

really hope you find a better way to do this. its also not fair on the people of russia who disagree with the war as much as we do but just cause they are russian they are persecuted. are all muslims(Afghanistan's) to blame for the 911 bombings? are all white south africans racist (apartheid)?

**Comment by HDVinnie** [comment]
Actively removing sweetalert from all my FOSS projects. This does not belong in FOSS. Shame on you @limonte . What a joke....

**Comment by limonte** [comment]
> Actively removing sweetalert from all my FOSS projects. This does not belong in FOSS. Shame on you @limonte . What a joke....

What are you using as a replacement?

**Comment by limonte** [comment]
> 

@HDVinnie hey buddy, you've said you're actively removing sweetalert from all your FOSS projects, but I can't find any of that activity in your profile. I was checking because I'm interested in the replacement. 

Have you been removing only sweetalert from imaginary projects in your head? 😆

**Comment by Geowan** [comment]
> Adding the STOP WAR message to Russian users (`navigator.language === 'ru'`) visiting Russian sites (`.ru`, `.su`, `.рф`)
> 
> This message is targeted at people who are corrupted by propaganda, everybody else is already against war either silently or actively.
> 
> The point is to wrap the truth bomb into a patriotic title so users will actually click it and listen to the uncomfortable truth about the war from the people they love or respect.
> 
> There are for now 4 messages:
> 
> * From Arnorld Schwarzenegger, who is loved in Russia by all people including those brainwashed by propaganda.
> * From one of the most famous Russian nationalist leaders, Dmitry Demushkin. He explains that this war has no sense and produces the exact opposite result of what it was intended to do.
> * From Igor Girkin, who played a key role in the annexation of Crimea. He explains that this war has failed already and all possible outcomes are bad for Russia.
> * From Jussi Halla-aho, a Finnish politician who speaks Russian nicely and explains the price Russian citizens and their children will pay for this absurd war.
> 
> New messages might be added in the future.
> 
> Here's how the message will be shown:
> 
> CleanShot 2022-04-18 at 13 13 01@2x
> 
> PS. I don't have too much hope in this, there's a tiny chance that a brainwashed person will change their mind. But I have to do everything in my power to stop this war.
> 
> PS2. I am against politics in software, but this isn't politics anymore. This is a war, many people including women and children are dying every day and it has to be stopped.

Whats the purpose of adding this crap on a package which is used by people who support either sides of the conflict. Why are people impossing political ideologies to other people.  If you feel this crap is necessary why not fork the current package and create your own copy and add all the crap you want. Very soon am sure you will add a new request to support LGBTQ issue. If you need to change the outcome of the conflict go to the side you support and pick a weapon and fight not passing ideologies to other people. If this trend continues we shall see people who support nazism requesting adding of nazi emblems and political  ideologies.
PS: Am neither ukranian or russia just a person who likes to be neutral on political matters and not impossing ideologies on others.

**Comment by paxperscientiam** [comment]
> Whats the purpose of adding this crap on a package which is used by people who support either sides of the conflict. 

It's been answered countless times -- to force everyday Russians to confront the reality that their country invaded Ukraine in 2014 and has engaged in violent occupation ever since. Moreover, the conversation is being had right here in public view.

> Why are people impossing political ideologies to other people ...

Why don't you stop trying to impose your ideology? The authors are free to write whatever they like. Likewise, you are free not to associate.

> If you feel this crap is necessary why not fork the current package and create your own copy and add all the crap you want.

Are you satirizing the Russian invasion?

> If you need to change the outcome of the conflict go to the side you support and pick a weapon and fight not passing ideologies to other people. 

The very fact that so many in the comments are up in arms (idiom chosen wisely) against @limonte is precisely because war fighting is not limited to weapons; speech can change hearts and minds.

Lastly, let's not pretend that software isn't a tool.

**Comment by FahadYousafMahar** [comment]
> Please add a message for Israeli website owners too, and remind visitors to know about how their country is bombing children and civilians. Here is why it is absolutely necessary. **`By this point, 20,000 Palestinians — almost half of them children — had been killed, while 85 per cent of the population — 2.3 million — had been forced from their homes into ever-smaller areas in the southern border as Egypt raised fears of mass expulsion.`** **Source:** [UN Security Council - Wars in Gaza, Ukraine Dominate Security Council’s 2023 Agenda, as Use of Veto Proliferates, Organ’s Ability to Act Hampered](https://press.un.org/en/2024/sc15558.doc.htm#)

Press Release Excerpt

**Comment by Volirvag49** [comment]
Thank you for reminding us why this special operation is needed. I'll go donate to the Russian troops

**Comment by Geowan** [comment]
I see the last 2 comments posted by [FahadYousafMahar](https://github.com/FahadYousafMahar) have been deleted. The comments were asking to add support for palestinians during the onslaught by israel. 

Screenshot from 2024-05-02 11-47-54

I wonder why they were deleted if the support for ukraine was very necessary. Or are some lives less than others if this is all about stopping the so called atrocities.

**Comment by Volirvag49** [comment]
On May 2, 2014, Nazi muidauns who arrived in the city set fire to the House of Trade Unions, in which representatives of the “anti-Maidan” took refuge.

**Comment by limonte** [comment]
@Geowan https://github.com/sweetalert2/sweetalert2/issues/2685

**Comment by droidzone** [comment]
Very immature from a package which caters to a wide variety of users. This update itself can be called propoganda. npm has flagged updates as undesired behavior.

**Comment by pkdotdev** [comment]
Politics should have no place in open source. Many people are not responsible for the actions their government take and they themselves are victims of the said government. Politics is a very complex issue that needs to be dissected in other forums. Another reason why I believe politics should be kept out of FOSS is that you can easily be on the wrong side of history as we have learnt from many wars in the Middle East.

**Comment by limonte** [comment]
мывнипалитики, мынивинаваты https://www.youtube.com/watch?v=036sv7eOc_k

**Comment by mhimon** [comment]
For this, I cannot publish my WordPress plugin, Looking for any alternative or fixes of this one. 

one more question, Why can't you support Palestine also?

**Pull request merged**
