### PR TITLE
Bump browser-sync dependency

### PR DESCRIPTION
**Pull request by gverni**
This version include the fixes for `axios` package vulnerability (through the `local-tunnel` dependency)

### CODE REVIEW

**Comment by gverni** [comment]
@limonte this is not mandatory because the `local-tunnel` version (and in turns the `axios` one) is already updated. Up to you if you want to merge it or reject it.

**Comment by zenflow** [comment]
> and thanks to semver and caret ranges we don't need to update package.json on every change in versions of dependencies.

This is true only if you're using `npm` and not `yarn`..

This project has [instructions that seem to indicate we're using both/either](https://github.com/sweetalert2/sweetalert2#contributing). 

It's obvious but still worth noting that the same dependencies won't be installed by both. 

It's also worth noting that adding & upgrading dependencies with npm (which updates just package.json) would screw things up for yarn users, who need the yarn.lock file to be aligned with the package.json.

@limonte do you think we should standardize on one?

**Comment by limonte** [comment]
Appreciate your feedback @zenflow 

Even though I agree with you on the technical side of the issue, I disagree that we should complicate the contributing instructions. I prefer to keep them as simple as possible.

As one of the maintainers of this project, I never faced people complaining nor about different versions installed by yarn/npm neither about updating `yarn.lock` file.

But, I'll keep that in mind and improve the docs in case new contributors will be facing these issues.

**Comment by limonte** [comment]
> It's also worth noting that adding & upgrading dependencies with npm (which updates just package.json) would screw things up for yarn users, who need the yarn.lock file to be aligned with the package.json.

@zenflow FYI npm v7 will support `yarn.lock`: https://blog.npmjs.org/post/186983646370/npm-cli-roadmap-summer-2019 :tada:

**Pull request closed without merging**
