### PR TITLE
feature(ci-build): check for magic numbers with buddy.js

### PR DESCRIPTION
**Pull request by limonte**
I got this idea from https://github.com/ryanmcdermott/clean-code-javascript#use-searchable-names

Nobody like magic number in the codebase, [buddy.js](https://github.com/danielstjules/buddy.js) will prevent contributors from adding them.

### CODE REVIEW

**Comment by zenflow** [comment]
This check would be more useful if it got run by contributors during local development, before opening a PR.

**Comment by zenflow** [comment]
Also I think it might be better to do this check with eslint (which we're already using) .. we can extend the `standard` eslint config with the [no-magic-numbers](https://eslint.org/docs/rules/no-magic-numbers) rule in eslint core. Then there is one less parsing of all the js code and one less task to run.

**Comment by limonte** [comment]
> Also I think it might be better to do this check with eslint (which we're already using) 

We are using standard for this project which doesn't require `.eslint.json` or any other config, it just works. If we replace it by `eslint` we'll have one more config file in the repo.

Let's not merge this just because I found another one `<cool>.js` library :)

**Comment by zenflow** [comment]
> it just works

Yeah, I agree. This is the major benefit of using `standard` as opposed to eslint directly. Extending the `standard` config seems tempting sometimes, but the `standard` is "good enough" (though I wish it included rules for ES2015+, like [no-var](https://eslint.org/docs/rules/no-var)) and extending it in my experience is not so simple.

**Pull request closed without merging**
