### PR TITLE
feature: add onAfterClose config option

### LINKED ISSUE #1004: Implement onAfterClose
I have a script which compensates for the background moving when opening and closing a modal.

To get this working i need to run some code onBeforeOpen and onAfterClose (the latter function is not available right now).

Would it be possible to implement this? I would be happy to provide a Pull Request.

### PR DESCRIPTION
**Pull request by limonte**
Resolves #1004 

All credits for this PR are going to @Baune8D :beers: I made this PR to save his time from resolving Git conflicts.

I just cherry-picked his commits and resolved conflicts after the recent refactoring https://github.com/sweetalert2/sweetalert2/pull/1026

### CODE REVIEW

**Comment by Baune8D** [comment]
@limonte Happy to help out! :)

**Comment by limonte** [comment]
Released in [v7.17.0](https://github.com/sweetalert2/sweetalert2/releases/tag/v7.17.0) :tada:

**Comment by Baune8D** [comment]
@limonte Cool! Would it be possible to mention me in the contributors section of the readme? It would mean a great deal to me? :)

**Comment by limonte** [comment]
> @limonte Cool! Would it be possible to mention me in the contributors section of the readme? It would mean a great deal to me :)

I would like that, but the picture in https://github.com/sweetalert2/sweetalert2#contributors is generated automatically by OpenCollective (https://opencollective.com/SweetAlert2/contributors.svg?width=890&button=false) based on the repo commit history.

On the other hand, after [cherry-picked commits](https://github.com/sweetalert2/sweetalert2/pull/1030/commits) were squash-n-merged into [one commit](https://github.com/sweetalert2/sweetalert2/commit/30f7a1ace9ac39b8ef5a463efe4c4846ef680d95), for some reason GitHub (or Git) put just me as an author of the squashed commit, instead of both of us as I was expecting :/

Sorry for this inconvenience, I would really like to see you in the list of contributors, but apparently I don't know Git good enough :/

**Comment by Baune8D** [comment]
@limonte No worries, i will just have to contribute again soon then :)

**Pull request merged**
