### PR TITLE
attempts to fix cognitive complexity

### PR DESCRIPTION
**Pull request by ConSou**
attempts to fix issue #1531

### CODE REVIEW

**Comment by limonte** [comment]
This PR also decreases the **readability** of the code which should be one of our top priorities in order to keep the codebase maintainable.

I'm closing this PR, sorry @ConSou but it went wrong way and increases the cognitive complexity instead of decreasing it.

**Comment by limonte** [comment]
I also added eslint rules to enforce curly braces always: https://github.com/sweetalert2/sweetalert2/pull/1534

**Comment by ConSou** [comment]
Ok, @limonte this all makes sense.  I can take another try at improving the complexity if you'd like.  In looking at the code in the close function, I don't see a lot of instances of breaks in flow or nesting.  Do you have any thoughts on where to start?  I'm pretty new to cognitive complexity but am happy to learn and help out!

**Comment by gverni** [comment]
@ConSou thanks for trying to help! Before trying to reduce cognitive complexity, please have a look to [this document](https://www.sonarsource.com/docs/CognitiveComplexity.pdf). Appendix B is especially useful to try and work out how code climate scored the cognitive complexity of a function. In this specific case, the cognitive complexity is just a little over the threshold, so the change will probably be small. Read carefully that document and have another go! 👍

**Comment by ConSou** [comment]
@gverni, thank you for this resource!  I will look over it and try again

**Pull request closed without merging**
