### PR TITLE
TypeScript: support sweetalert2 modules in dist and src folders

### PR DESCRIPTION
**Pull request by limonte**
Fixing the issue I described in https://stackoverflow.com/questions/57321486

TLDR: right now `import Swal from 'sweetalert2/dist/sweetalert2.js'` isn't TS-friendly and producing this error:

```
Could not find a declaration file for module 'sweetalert2/dist/sweetalert2.js'. 

ts(7016)
```

This PR is based on @toverux's answer https://stackoverflow.com/a/57323500

### CODE REVIEW

**Comment by toverux** [comment]
Hah, it's a nice idea to use globs in the .d.ts file to cover both src and dist!
It is also possible to type every .js module in src/ and derive the type of the dist/ files from that, that would be the cleanest and definitive method to do it, however I don't think our customers often use internal symbols and submodules (even `src/SweetAlert.js`), and therefore this approach may be way too invasive for this particular project.

**Comment by limonte** [comment]
> Hah, it's a nice idea to use globs in the .d.ts file to cover both src and dist!

I thought so too, but for some reason, TS isn't able to understand them. TS2306: File '.../node_modules/sweetalert2/dist/sweetalert2.d.ts' is not a module. So I removed wildcards.

**Comment by limonte** [comment]
> Hah, it's a nice idea to use globs in the .d.ts file to cover both src and dist!

Yup, wildcards are working nicely, I tried 

```js
declare module 'sweetalert2/*/sweetalert2.*js' {
```

to avoid copy-pasting, but

```
Pattern 'sweetalert2/*/sweetalert2.*js' can have at most one '*' character.ts(5061)
```

Thanks again @toverux for your valuable (as always) input!

**Comment by kevin82222** [comment]
Hi there,

I've been using sweetalert2 for quite a while and am currently on version `11.15.10`. Recently, I started migrating my project to TypeScript and noticed an issue when importing sweetalert2:

```
Could not find a declaration file for module 'sweetalert2/dist/sweetalert2.js'. '/web/download/node_modules/sweetalert2/dist/sweetalert2.js' implicitly has an 'any' type.
```

I understand that previous fixes addressed similar issues. However, since I'm using a much later version, I wonder if this error might be related to additional TypeScript configuration settings or other factors in my environment.

Could you please advise on any extra steps or configuration adjustments needed to resolve this issue?

Thank you for your time and assistance.

Best regards,
Kevin

**Comment by limonte** [comment]
@kevin82222 https://github.com/sweetalert2/sweetalert2/issues/2187#issuecomment-2305574371

**Comment by kevin82222** [comment]
Oh! It's perfect~
Many thanks!

**Pull request merged**
