### PR TITLE
changed button colors to be WCAG compliant

### PR DESCRIPTION
**Pull request by dezteague**
Updated the color contrast on the orange, blue, and gray buttons to pass WCAG 2.0 AA standard.  Previous colors did not pass the 4.5:1 ratio expected

### CODE REVIEW

**Comment by limonte** [comment]
Hey @dezteague and thank you for the contribution!

Could you please tell me how to check the color contrast of a button or give any reference to any guide?

**Comment by dezteague** [comment]
Hi there,

Initially, I used the Axe browser extension
<https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US>
to check for accessibility failures. Highly recommend that tool!  Then, I
went to https://webaim.org/resources/contrastchecker/, plugged in the old
hex code values, and adjusted the contrast until I found a color that
passed.

Hope this helps!

Cheers,
Dezireé

**Review by limonte — APPROVED** [review]
Thank you @dezteague!

**Pull request merged**
