### PR TITLE
Disable body scroll when modal is shown (iOS)

### LINKED ISSUE #1246: iOS, Safari: document scrolling isn't prevented when a modal is shown
Actual: It's possible to scroll the document under the modal backdrop

Expected: the scrolling isn't possible, because `overflow-y: hidden` on `<body>`

### PR DESCRIPTION
**Pull request by limonte**
Fixes #1246

@gverni could you please double-check this fix? thanks!

### CODE REVIEW

**Comment by gverni** [comment]
Sure @limonte, i’ll let you know shortly...

**Comment by gverni** [comment]
Hi @limonte, I tested it on both chrome and safari on IOS and it works fine! (i.e. no scrolling) Well done!

**Comment by limonte** [comment]
Thank you @gverni 

I wanted to handle this one and https://github.com/sweetalert2/sweetalert2/issues/1444 before moving forward with the new major :rocket:

**Pull request merged**
