### PR TITLE
Add Android 4.4 support

### LINKED ISSUE #1071: Android 4.4 WeakMap is not defined
Uncaught ReferenceError: WeakMap is not defined.

I included polyfill, without success

### PR DESCRIPTION
**Pull request by limonte**
Fixes #1071 

- Add Android 4.4 tests with SauceLabs (CI cron builds)
- Add `WeakMap` polyfill
- Add `Map` existence check, use it only if defined

### CODE REVIEW

**Comment by limonte** [comment]
Here's the useful gist how to install Android 4.4 emulator: https://gist.github.com/limonte/a6d00f09edccfd66b6a02fd58551b796

**Comment by zenflow** [comment]
A few issues with how we're getting WeakMap here, and one suggestion

1. As a library I think changing the global environment like in privateProps.js is too intrusive and could cause some users some confusing issues. This can be avoided and WeakMap can be loaded in just a local lexical scope.
2. I'm not so confident in the WeakMap implementation used here.. I'm not sure it was ever tested or not and it seems like it was intended to be more of a demonstration of what you can do with Symbols rather than a serious production-ready implementation of WeakMap. 
3. Lastly, I think we shouldn't be reusing code from the web by copy-pasting it into our repo. Npm is great. It's possible to install packages as devDependencies and have them included in in the bundle at build-time.

So my suggestion is to choose a WeakMap polyfill from npm, have it included in the bundle, and use it such that it doesn't patch the global environment but instead use the exported WeakMap.

**Comment by limonte** [comment]
> As a library I think changing the global environment like in privateProps.js is too intrusive and could cause some users some confusing issues. This can be avoided and WeakMap can be loaded in just a local lexical scope.

Valid point, will do :+1:

> I'm not so confident in the WeakMap implementation used here.. I'm not sure it was ever tested or not and it seems like it was intended to be more of a demonstration of what you can do with Symbols rather than a serious production-ready implementation of WeakMap.

I think it's good enough as a temporary solution, at least all tests are passing. Android 4.4 support will be (hopefully) dropped next year and that polyfill will be removed completely.

> Npm is great. 

Not quite. Actually, IMO it's in a horrible state right now, here's why https://medium.com/@caspervonb/the-internet-is-at-the-mercy-of-a-handful-of-people-73fac4bc5068

> So my suggestion is to choose a WeakMap polyfill from npm, have it included in the bundle, and use it such that it doesn't patch the global environment but instead use the exported WeakMap.

Do you have any suggestions? I didn't find anything good yesterday.

**Comment by limonte** [comment]
> Not quite. Actually, IMO it's in a horrible state right now, here's why https://medium.com/@caspervonb/the-internet-is-at-the-mercy-of-a-handful-of-people-73fac4bc5068

Just a small demonstration of a ridiculous state of npm ecosystem:

```
npm-remote-ls --development=false babel-core
└─ number-is-nan@1.0.1 
```

Just to clarify, `babel-core` is using `number-is-nan` as one of its sub-dependencies and `number-is-nan` is the poNyfill which provides nothing more than `function isNan(x) { return x !== x; }`

Can we call this "great"? I don't think so. But it's the best we have right now.

**Pull request merged**
