### PR TITLE
JSON Loadout Plugin

### PR DESCRIPTION
**Pull request by ForgivenNin**
I really enjoy the simplicity in the design of these alert tabs, and I wanted to take it one step further by allowing the user to make a loadout that can be plug-and-play friendly.

So far, I made a JSON file with all the default configurations in a single, objectified array, so that more loadouts can be included. From there, the JavaScript object property reader will look at each configuration accordingly and ultimately produce the alert.

At the time of making this draft pull request, i have not figured out how the properties will be read or what I should do about properties that require more properties _(if you look at the [sweetalert2 website](https://sweetalert2.github.io), you'll see what I mean)_. If anybody would like to join me in the production of this, or give some thoughts and opinions, it would be greatly appreciated.

### CODE REVIEW

**Comment by ForgivenNin** [comment]
Of course, once the draft is ready, I'll update it to the current commit of the `master` branch.

**Comment by limonte** [comment]
> I wanted to take it one step further by allowing the user to make a loadout that can be plug-and-play friendly.

What's a loadout, when and where it can be used?

**Comment by ForgivenNin** [comment]
The loadout is `template.json` as an array of the alert configuration properties, and it will be read when the alert is loaded in runtime.

**Comment by limonte** [comment]
> The loadout is `template.json` as an array of the alert configuration properties, and it will be read when the alert is loaded in runtime.

I'm still not getting it. Could you share sore reading about it?

**Comment by ForgivenNin** [comment]
I do not have any documentation to provide, but I did make my comment before yours more thorough.

**Comment by limonte** [comment]
No, it's not.

**Pull request closed without merging**
