### PR TITLE
fix: introduce 100ms delay before focusing the prev active element

### LINKED ISSUE #900: Dismiss with Enter, bubbles back to input[type=text] and retriggers
If I submit a bad text field value with the Enter key, which calls swal('bad input'), then dismiss the alert with the Enter key, the keyup event is also delivered to the original text input field, thus immediately retriggering the alert.  This doesn't happen with JavaScript alert().

This retriggering doesn't happen where a button with focus is activated by Enter.

### PR DESCRIPTION
**Pull request by limonte**
Fixes #900

### CODE REVIEW

**Comment by toverux** [comment]
The famous `setTimeout(fn, 0);` trick to run the function in a future event loop doesn't works?

**Comment by limonte** [comment]
> The famous setTimeout(fn, 0); trick to run the function in a future event loop doesn't works?

Nope, I tried it first, but no luck. I don't like magical numbers like `100` in this case, but hopefully, the reference to the issue will help for those who will read/maintain the code in future.

**Comment by limonte** [comment]
I glad that we added IE tests and AppVeyor, it just caught the small regression in IE :muscle:

**Comment by zenflow** [comment]
>I'm glad that we added IE tests and AppVeyor CI, it just caught the small regression in IE

Sorry, what do you mean? 

Issue #900 affects all browsers, or just IE11?

**Comment by zenflow** [comment]
There must be a more elegant solution to this issue, that might prevent future similar issues. At first look, I don't think this PR gets to the root of the problem. I can look deeper into this later

**Comment by limonte** [comment]
> Sorry, what do you mean?
> Issue #900 affects all browsers, or just IE11?

All browsers, but the first version of this PR was failing in IE: 

- https://ci.appveyor.com/project/limonte/sweetalert2/history
- https://ci.appveyor.com/project/limonte/sweetalert2/build/117

 > There must be a more elegant solution to this issue, that might prevent future similar issues. At first look, I don't think this PR gets to the root of the problem. I can look deeper into this later

Agree. I'd be more than happy if you can come up with the less hacky solution.

**Comment by zenflow** [comment]
This fix only works if the user presses the enter key very quickly. If they delay > 100 ms between keydown and keyup the issue is still there. Easily reproduced in the sandbox with the commit i just added.

**Comment by zenflow** [comment]
Hmm.. but it looks like `window.alert` has that issue too.. if you dismiss the alert with Enter and delay a second before releasing the Enter key, you see the same effect.. so I think fixing that that is out-of-scope

**Comment by zenflow** [comment]
I think what Chrome is doing is returning the focus immediately, but filtering the Enter event for ~ 500 - 1000 ms .. which is a good safe amount of time to be sure the user isn't just pressing the Enter key slowly.

Is there any unintrusive way we could do the same?

**Comment by limonte** [comment]
> This fix only works if the user presses the enter key very quickly. If they delay > 100 ms between keydown and keyup the issue is still there. Easily reproduced in the sandbox with the commit i just added.
>
> Hmm.. but it looks like window.alert has that issue too.. if you dismiss the alert with Enter and delay a second before releasing the Enter key, you see the same effect.. so I think fixing that that is out-of-scope

Well, the result is perfect in its alignment with the native alert? :)
- short press - same as alert
- long press - same as alert

PS. I rebased to master and removed changes in the sandbox as those shouldn't be in the PR.

**Comment by zenflow** [comment]
@limonte No because of the timing. Play with it. With a swal you have to press *really* fast (< 100 ms) or you see the bug. With Chrome it seems to suppress the keyup event for a longer time (but still seems to give focus to the input immediately).

**Comment by zenflow** [comment]
> PS. I rebased to master and removed changes in the sandbox as those shouldn't be in the PR.

That code is helpful within the scope of this PR/branch. Wasn't intended to merge. If I do this in the future please let's wait until it's ready to merge to remove it.

**Comment by limonte** [comment]
> No because of the timing. Play with it. With a swal you have to press really fast (< 100 ms) or you see the bug.

100ms seems to be an average keypress duration: 

- https://stackoverflow.com/q/22505698/1331425
- https://stackoverflow.com/a/4098858/1331425

I'm okay to increase it though, maybe **200ms** would be better - still too short to be noticeable, but longer than 167ms calculated here https://stackoverflow.com/a/4098779/1331425

**Comment by limonte** [comment]
here's the tiny jsfiddle for detecting your keypress duration: http://jsfiddle.net/Wk7jR/720/

For me, it's 40-50ms, so **200ms** will theoretically match non-tech persons.

**Comment by zenflow** [comment]
> 100ms seems to be an average keypress duration [...] I'm okay to increase it though [...] 200ms will theoretically match non-tech persons

If the distribution of keypress durations was normal, 100 ms would work roughly half of the time. Just a reminder that we would need to use a longer time than the average non-tech person. It might be difficult to choose a time that covers that and doesn't delay focusing on the element for the fast users.

What do you think about setting the focus immediately and filtering the keyup event from it's event handler?

**Comment by zenflow** [comment]
> What do you think about setting the focus immediately and filtering the keyup event from it's event handler?

... for a duration of maybe say, 500 ms?

**Comment by limonte** [comment]
> What do you think about setting the focus immediately and filtering the keyup event from it's event handler?

Could you please submit a PR with that solution?

**Comment by zenflow** [comment]
@limonte Check the issue, lets talk about the solution there some more

**Comment by limonte** [comment]
Since there's no better solution, I'll merge this PR.

**Pull request merged**
