### PR TITLE
Dev/unify tests with active development

### PR DESCRIPTION
**Pull request by zenflow**
So with this PR I propose switching from Testem + another different custom test harness to [Karma](https://karma-runner.github.io/2.0/index.html) which should satisfy the uses of both of it's predecessors. 

This is so we can run all our "active development" tasks as one integrated task, definitively closing issue #821, and also cleaning up the [duplicated test harness](https://github.com/sweetalert2/sweetalert2/issues/821#issuecomment-357591693).

The main problem that I ran into with Testem was, although it was designed to run in both "active development" mode and "continuous integration" mode, "active development" mode does not produce line-by-line readable output through stdout.. instead it draws on the console grid of characters.. so it's output could not be easily combined with the output from the other gulp tasks (building, linting). By changing test harnesses, the output from the tests can be nicely interleaved with the output from the other gulp tasks.

Also, it seems like karma has pretty good community support 

Also, the development experience is pretty good... anyone care to try?

### CODE REVIEW

**Comment by zenflow** [comment]
> do you think that we should include testing in gulp watch? IMO that would be too much https://github.com/sweetalert2/sweetalert2/issues/821#issuecomment-362804704

There currently *is* testing in `gulp watch` (a.k.a `npm start`). But it's a different test harness than what runs in CI. This just fixes that by replacing both harnesses with Karma.

Active development mode in Karma is fast, not nearly as slow like running `npm run check:test` is now, and it only runs when you visit it in a browser (and it handles reloading as necessary).

**Comment by zenflow** [comment]
Even if unit tests aren't in scope of `npm start` I want something in our package scripts to run unit tests in "active development" or "watch" mode.

But I don't see why you would want to start and manage two processes to do the same general thing instead of one.

**Comment by limonte** [comment]
Apologies @zenflow it took 2 weeks for me to review this contribution!

I'm very happy with switching to Karma, probably that means that we will finally be able to run tests agains IE11, Android browser, whatnot by using https://github.com/karma-runner/karma-browserstack-launcher

One question from me: you removed `test/sandbox.html` and didn't provide any replacement for it, I loved that small and simple sandbox, it was helpful with quick playing around with SweetAlert2. What would be a replacement for that with the new approach?

**Comment by zenflow** [comment]
Check out this new line in the README:

> http://localhost:8080/debug.html shows results in browser console. Also a good place to experiment with swal. Doesn't refresh when build or tests change

I think offering this environment to experiment offers a couple advantages
- Encourages running the tests frequently when you're working on SweetAlert2 code
- Encourages containing your experiment in an actual test that can be repeated

Give it a try and let me know what you think. Tests run for me in ~ 1.5 - 2 seconds.

**Comment by zenflow** [comment]
> I think offering this environment to experiment offers a couple advantages

The sandbox offers it's own advantages. I'll add it back. Useful for getting the visual effect/experience during design-time, something you can't really write unit tests for.

**Comment by zenflow** [comment]
Worked a bit on adding IE11 to our test suite..

There's a lot of failing tests that need to be sifted through and fixed like 06af2c53f21f5683d5e873deffa5e5459fed4aee. My intuition tells me it's mostly the test (not the source) code that has portability issues.

With d9153377b7951af8776f7d2801f064bfe7432cdc unit tests are set to run against IE11 also, so this branch will fail on environments where IE11 can't run, i.e. anywhere but Windows. Looking for a good solution for including IE11 as much as possible in our development workflow. Maybe of use: (karma-virtualbox-ie11-launcher)[https://www.npmjs.com/package/karma-virtualbox-ie11-launcher]

I brought in babel to transpile our tests so will be able to run in IE11, and webpack to give us `require` and `import` ❤️.

**Comment by limonte** [comment]
Great stuff @zenflow! Thanks a lot for keeping IE11 in mind!

> I think offering this environment to experiment offers a couple advantages
> 
> Encourages running the tests frequently when you're working on SweetAlert2 code
> Encourages containing your experiment in an actual test that can be repeated

Hm, in some cases, e.g. playing with SASS variables, I just need to play around with the simple html with the single swal in it, tests are unnecessary and not helping anyhow.

**Comment by zenflow** [comment]
@limonte Please review. I've rebased my work without deleting sandbox.html, squashed a bunch of commits, and made some additional changes. 

I'd like to finish IE11 compatibility with tests in another PR if that's ok. I've disabled testing against IE for now so the CI badges don't go red.

--- 

Step 4 now looks like:

To begin active development, run npm start. This does several things for you:

- Lints your code
- Builds the dist folder
- Serves sandbox.html @ http://localhost:8080/ (browser-sync ui: http://localhost:8081/)
- Serves unit tests @ http://localhost:3000
- Re-lints, re-builds, re-loads and re-tests as necessary when files change

**Comment by limonte** [comment]
I just published a new patch release, the output produced by Karma is perfect, love it!

**Pull request merged**
