### PR TITLE
Update positioning tests

### PR DESCRIPTION
**Pull request by gverni**
Removed deprecated `customContainerClass` property.

### CODE REVIEW

**Comment by gverni** [comment]
@limonte what's the strategy for test of deprecated feature? Should we update those tests or just remove them in favour of the new test for `customClass` already developed? 

Specifically I'm talking about the following tests: 

https://github.com/sweetalert2/sweetalert2/blob/42ef2138eb36bdc82b05cc897b5a72ce4505e8c3/test/qunit/tests.js#L187-L188

https://github.com/sweetalert2/sweetalert2/blob/31d4f1412fb69859771e09b3c9434f232b492160/test/qunit/params/input.js#L18

https://github.com/sweetalert2/sweetalert2/blob/42ef2138eb36bdc82b05cc897b5a72ce4505e8c3/test/qunit/tests.js#L452

https://github.com/sweetalert2/sweetalert2/blob/42ef2138eb36bdc82b05cc897b5a72ce4505e8c3/test/qunit/tests.js#L143

I'm happy to update the above if you think it's useful

**Comment by limonte** [comment]
Well, they are still features. Even though, they are deprecated, we should support them during the current major release and they should be covered by tests. So, no action needed.

**Comment by limonte** [comment]
Deprecated features and related tests will be removed altogether for the next major.

**Pull request merged**
