### PR TITLE
Form builder - adds multiple form inputs and form api

### PR DESCRIPTION
**Pull request by samturrell**
Hi all,

I started building this a while ago (like over a year ago) and just moved it over to the new repo with the new changes.

Just wondering if I should carry on with this as a feature or abandon?

## Details

It's currently not possible to have more than a single input in the modal. This PR would allow the user to define as many inputs as they want in a fairly flexible but uniform way using the following format:

```js
{
  label: '',
  placeholder: '',
  type: '', // text, textarea, select, file, range, checkbox, radio
  value: '',
  options: {}, // For select. checkbox, radio
  config: {}, // Input specific config (currently only for range)
  validator (value) {},
  attributes: {},
  classes: '',
  events: {} // Attach custom events to each input (change, keyup, focus, hover, custom...)
}
```

It also cleans up the dom a fair bit by only rendering what it needs to rather than all form elements on load regardless of the users needs.

This could also open up the ability to render other inputs within the modal in response to events (see https://github.com/sweetalert2/sweetalert2/blob/717e75ce2438be12ad9138d2284b3b21ae009ab6/src/utils/form.js#L13) using another public api method such as `swal.addInput({ })`. Use case here could be a radio for "Would you recommend us to a friend?" and if they select no, you could add a textarea for "Reason" etc.

On a side note, whenever i commit, it seems to commit all files regardless of whether i add them to the commit or not (see `.idea` and `dist` folders). Looks like the pre-commit hook doing it, is this desired functionality? The `.idea` folder should probably be gitignored on my system, granted but seems strange to commit everything regardless.

### CODE REVIEW

**Comment by limonte** [comment]
I just removed committed dist and IDE files

**Comment by limonte** [comment]
YAY! Thanks @samturrell for submitting this code and sorry for the delay in my response. I'm in the vacation-mode currently, making :snowman: in cold Lapland :)

I love this feature, it will cover a ton of real use-cases. I even willing to increase the bundlesize limit since it currently adding around 4KB.

Question: what should be the result value in case of multiple inputs? Should we introduce the `id` key for the input definition object so the returning value will be the object like this:

```
{
  input1-id: input1-value,
  input2-id: input2-value
  ...
}
```

**Comment by samturrell** [comment]
Do you think the inputs should be an array or an object with the key being the input name? With an object we have the advantage of Unique field names, but makes it a bit more difficult as I have to pass the field name down through multiple functions to build up the dom

**Comment by limonte** [comment]
> Do you think the inputs should be an array or an object with the key being the input name?

An object, or even a Map, as @toverux suggested in https://github.com/sweetalert2/sweetalert2/issues/812#issuecomment-357219832

**Comment by User934903920432** [comment]
`This PR would allow the user to define as many inputs as they want in a fairly flexible but uniform way using the following format:`
How would we define multiple inputs with this currently? As I can only see one placeholder for example.
Maybe for multiple inputs it would be nice to add multiple objects, e.g this would be a nice format:

```
inputs = {
    username: { label: '', placeholder: '', type: '',  value: '', options: {},  config: {},  validator (value) {}, attributes: {}, classes: '', events: {}  },
    password: { label: '', placeholder: '', type: '',  value: '', options: {},  config: {},  validator (value) {}, attributes: {}, classes: '', events: {}  },
    submit: { label: '', placeholder: '', type: '',  value: '', options: {},  config: {},  validator (value) {}, attributes: {}, classes: '', events: {}  },
}
```

Or maybe even like this.
```
var username = { label: '', placeholder: '', type: '',  value: '', options: {},  config: {},  validator (value) {}, attributes: {}, classes: '', events: {}  };
var password = { label: '', placeholder: '', type: '',  value: '', options: {},  config: {},  validator (value) {}, attributes: {}, classes: '', events: {}  };
var submit = { label: '', placeholder: '', type: '',  value: '', options: {},  config: {},  validator (value) {}, attributes: {}, classes: '', events: {}  };

swal({
    title: 'Form', 
    text: 'Form with multiple fields', 
    type: 'form',
    inputs: [username, password, submit]
})

```

Maybe also allow us to modify the containers of the input, I'm personally always using bootstrap for forms, but obviously not everyone is using that and might be using different frameworks.

So maybe like this ?
```
var username = { label: 'username', placeholder: 'Username', type: 'text' };
var password = { label: 'password', placeholder: 'Password', type: 'password' };
var submit = { label: 'Sign in', type: 'submit' };

swal({
    title: 'Form', 
    text: 'Form with multiple fields', 
    type: 'form',
    action: 'url',
    inputs: [username, password, submit],
    inputContainer: ['form-group row', 'col']
})
```

In this case it would generate something like this.
```
<form action="url">
    <div class="form-group row">
        <div class="col">
            <input type="text" placeholder="Username">
        </div>
    </div>
    <div class="form-group row">
        <div class="col">
            <input type="password" placeholder="Password">
        </div>
    </div>
    <div class="form-group row">
        <div class="col">
            <button type="submit">Sign in</button>
        </div>
    </div>
<form>
```

**Comment by samturrell** [comment]
Hi @User934903920432 - yep, the `inputs` property would accept any number of input objects as you mentioned in your first example.

For details on how fields can be added dynamically, you can check here https://github.com/sweetalert2/sweetalert2/blob/06143789ebbda33a585a726c5acc156eb9cc5949/test/sandbox.html

As for the multiple input containers, i don't think this would have a huge benefit to most users, and the example you've given would actually negate effects of the column anyway. You would be better off styling the form as a row, and the form groups as columns which would remove the need for the extra markup. However may be something to consider in the future maybe implementing a markup transformer, but again not really too important to most users. Thanks for the feedback!

**Comment by samturrell** [comment]
I'm back! I promise i'm working on this again. This feature has been in the making for around two years but i feel like this year is definitely the one... 👀 

I'll go ahead and close this PR as the codebase has evolved a long way since I opened it, and it won't be worth me fixing this branch. I'll PR another one when it's closer!

**Comment by limonte** [comment]
Yay! Welcome back @samturrell!

Two years per feature is totally fine, I know that from my own experience https://github.com/sweetalert2/sweetalert2/issues/25#issuecomment-359097183 🐌

**Comment by jonvaljean** [comment]
Hi
What is the status, if any, of a form builder in sweetalert2 ?  I have given swal-forms a try but could not get it to work, not at all sure why.
Such a feature would be super.
Thanks for letting me know if there is something available, coming, or if this is not going to happen.
Jon

**Pull request closed without merging**
