### PR TITLE
Font is inherited by default

### LINKED ISSUE #846: Change default font-family to system UI font
Currently, the font-family for dialogs is set to Helvetica Neue.

```css
.swal2-popup {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```

I'm not sure this is desired; I want the popup's font to be consistent with the rest of my app, so I end up overriding the above rule:

```css
.swal2-popup {
  font-family: inherit;
}
```

Would it make sense to remove the `font-family` property so that it will be inherited by default?

### PR DESCRIPTION
**Pull request by sloria**
This is a better default than Helvetica Neue.

closes #846

### CODE REVIEW

**Comment by limonte** [comment]
Thanks for your contribution @sloria 

What's your opinion about the future-proof `system-ui` font-family?

From https://css-tricks.com/snippets/css/system-font-stack/

> Chrome and Safari have recently shipped "system-ui" which is a generic font family that can be used in place of "-apple-system" and "BlinkMacSystemFont" in the following examples. Hat tip to J.J. for the info.

**Comment by limonte** [comment]
> What's your opinion about the future-proof system-ui font-family?

Well, this article explains it well: https://infinnie.github.io/blog/2017/systemui.html

**Comment by toverux** [comment]
Defining a font on alerts was a very opinionated choice in the first place.
This new default is not much better in my opinion. Why wouldn't we just let the browser apply the inherited font? Alerts would be more coherent with the rest of the page.

**Comment by limonte** [comment]
@sloria I'm the one who bringing a lot of confusions to this project! :D

After some thinking during my lunch I need to admit that you were right in the first place in #846 and @toverux is right.

Please amend your PR and set the `$swal2-font` to `inherit`. Sorry for not agreeing with your initial point right away :)

**Comment by sloria** [comment]
Done!

**Comment by limonte** [comment]
Released in https://github.com/sweetalert2/sweetalert2/releases/tag/v7.7.0

Thanks again @sloria :beers:

**Pull request merged**
