### PR TITLE
Refactor/extract withGlobalDefaults

### PR DESCRIPTION
**Pull request by zenflow**
Towards #1044

### CODE REVIEW

**Comment by zenflow** [comment]
With the deprecation warning I added last commit, the documentation site should be updated before publishing this

**Comment by zenflow** [comment]
@limonte 👍  Be sure not to publish before sweetalert2.github.io is updated in regards to Swal.mixin

**Comment by zenflow** [comment]
@limonte or users will get a deprecation notice saying to switch to using a method that's not documented yet

**Comment by limonte** [comment]
@zenflow roger!

**Comment by zenflow** [comment]
@limonte How are you liking `Swal.mixin` in practice?

**Comment by limonte** [comment]
> How are you liking Swal.mixin in practice?

Can't live without it :) `Swal.mixin` helped to eliminate tens of copy-pasted LoC with repetitive parameters.

**Comment by zenflow** [comment]
> @limonte 👍 Be sure not to publish before sweetalert2.github.io is updated in regards to Swal.mixin
> @limonte or users will get a deprecation notice saying to switch to using a method that's not documented yet

Eh, I guess we should get that documentation updated quickly since this is released in 7.19.0. I'll make a PR to the documentation site just adding the `Swal.mixin` method, and I think the rest of the edits (e.g. `swal` -> `Swal` can come in the new site.

**Comment by limonte** [comment]
> @limonte +1 Be sure not to publish before sweetalert2.github.io is updated in regards to Swal.mixin
@limonte or users will get a deprecation notice saying to switch to using a method that's not documented yet

Oops. I forgot about this, apologies. 

> I'll make a PR to the documentation site just adding the Swal.mixin method, and I think the rest of the edits (e.g. swal -> Swal can come in the new site.

:+1:

**Pull request merged**
