### PR TITLE
chore/Remove event-stream package

### LINKED ISSUE #1301: Get rid of the `event-stream` devDependency
Reasons:

- it's poorly maintained: https://github.com/dominictarr/event-stream/issues/113#issuecomment-423739893
- ⚠️ it's some kind of injection attack: https://github.com/dominictarr/event-stream/issues/116 

We're currently using it in one place, `utils/execute.js`: https://github.com/sweetalert2/sweetalert2/blob/13662349768bfdd98cfb91000e55bf2c3cfc3bb9/utils/execute.js#L2

### PR DESCRIPTION
**Pull request by gverni**
This PR is a WIP to remove usage of the event-stream package

Closes #1301

More details: https://github.com/dominictarr/event-stream/issues/116

### CODE REVIEW

**Comment by gverni** [comment]
Hi @limonte, @zenflow this is my proposal to get rid of event-stream. The strategy I've used is to aim to have a smaller, more readable code that just address the needs of our project. All of the three functions (`merge()`, `split()`, `map()`) have been replaced with functions that create a `Duplex` stream. Below some more details on each one of them: 

* `split()`
In our case the input is a character stream and we just need to split on line feed / carriage return. So this is the only case handled. Every time a new `chunk` is received, the `write` function checks if it contains a `/\r?\n/`. If it does, then it proceeds to splitting up the `chunk` and write to the stream all but the last one piece of the `chunk`. There are two possibilities for this last piece of `chunk`: 
  * Empty string (`''`): this means that the `chunk` was actually ending with `/\r?\n/`. And we use the empty string to initialise the `buffer`
  * A string: the `chunk` did not end with  `/\r?\n/` so we put the string into the `buffer`

* `map()`
In this one I simply execute the function passed as argument on the `chunk`, and I push the returned value into the stream. As you can see, the way this is called is now different (i.e. there is no need for the `callback` since this is called inside the `write()` of the `map` stream). On this one I'd really like to have your feed-back, because i'm not entirely sure that removing the callback is the right way of implementing this. 

* `merge()`
For this one I took the core of the implementation of `merge()` in `event-stream` and removed all the functions that we don't need: 
  * I removed the check of the arguments list. The assumption is that we are always calling this with at least 2 streams. I can add a simple check here if needed or put back the original code. 
  * I removed the handling of the `end` event because I assumed that we are using it only with `proc.stdout` and `proc.stdin`
  * I removed the handling of the `destroy` event
 All these assumptions makes the code smaller but less flexible and robust, so I'm more than happy to put the original code back if you think it's too risky 

I captured the output of both implementations for comparison:  
* [Output with `event-stream`](https://github.com/sweetalert2/sweetalert2/files/2612466/log-event-stream.txt)
* [Output with the new `stream-array`](https://github.com/sweetalert2/sweetalert2/files/2612467/log-stream-array.txt)

The only difference I could find is that the new implementation is removing blank line. 

I also did some profiling, and the new implementation does not add significant load on the processor. The `RegExp` related functions seems to be the only one that take more than 1 thick. You can find the output of the profiling [here](https://github.com/sweetalert2/sweetalert2/files/2612471/stream-array_profiling.txt)

I hope this explains a bit what I did. Let me know otherwise.

**Comment by gverni** [comment]
I removed the `event-stream` package. I've noticed that two of the packages used by `event-stream` are still there because they are used by other packages. Below the output of `yarn why` command: 

```
$ yarn why split       
yarn why v1.12.3
[1/4] 🤔  Why do we have the module "split"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "split@1.0.1"
info Reasons this module exists
   - "semantic-release#@semantic-release#release-notes-generator#conventional-changelog-writer" depends on it
   - Hoisted from "semantic-release#@semantic-release#release-notes-generator#conventional-changelog-writer#split"
...
$ yarn why map-stream
yarn why v1.12.3
[1/4] 🤔  Why do we have the module "map-stream"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "map-stream@0.0.7"
info Reasons this module exists
   - "gulp-tslint" depends on it
   - Hoisted from "gulp-tslint#map-stream"
```

Nevertheless, I'd be keen to keep the implementation as it is if you agree, so we have more control on it. 

On a different note, I've seen some other changes on `yarn.lock` file that are not related to the removal of the `event-stream` package. @limonte do you mind having a look to make sure I'm not messing up with this file?

**Comment by limonte** [comment]
`split` and `map-stream` are fine. `event-stream` is suspicious because of `flatmap-stream`, which was introduced in `event-stream@4.0.0`.

> On a different note, I've seen some other changes on yarn.lock file that are not related to the removal of the event-stream package.

That's alright :+1:

**Comment by limonte** [comment]
Manually tested everywhere, works perfectly

Thanks again, @gverni!🏅

**Pull request merged**
