### PR TITLE
Release script: make version commits to master

### PR DESCRIPTION
**Pull request by limonte**
Follow-up to #880

### CODE REVIEW

**Comment by limonte** [comment]
> We should change the git push command to git push origin master:master dist:dist --tags so you don't have to push master manually after this

Done.

**Comment by limonte** [comment]
Perfect! Thank you @zenflow for the detailed code review!

What about https://github.com/sweetalert2/sweetalert2/pull/875 - you don't like the change or you didn't have time to check it?

**Comment by zenflow** [comment]
I checked it out but didn't have time to make a review yet.. Doing that now. 👍

**Comment by limonte** [comment]
YAY! Just made a new patch release with one command and w/o any issues! :tada: :tada: :tada:

**Pull request merged**
