### PR TITLE
feature: add onAfterClose config option

### PR DESCRIPTION
**Pull request by Baune8D**
As described here #1004

### CODE REVIEW

**Comment by Baune8D** [comment]
@zenflow Yeah i see your point. Have a look at my latest commit. 

onClose has been moved further up in the function and made sync so it will always run before the actual disposal of the modal happens.

onAfterClose will now run async after the modal has been disposed.

I updated the tests to reflect this.

It might be a problem that onClose runs differently now, if someone is dependent on the old behaviour.

**Comment by Baune8D** [comment]
@zenflow travis-ci gives a weird error? Relevant tests seems to succeed though

**Comment by zenflow** [comment]
@Baune8D Travis failure is due to #986 .. I started another build ..

**Comment by limonte** [comment]
There are Gti conflicts after https://github.com/sweetalert2/sweetalert2/pull/1026

I decided to save you time @Baune8D and create a new PR with your commits cherry-picked: https://github.com/sweetalert2/sweetalert2/pull/1030 

I'm closing this PR, thanks again @Baune8D :beers: for your contribution and @zenflow for catching issues!

**Comment by limonte** [comment]
Released in [v7.17.0](https://github.com/sweetalert2/sweetalert2/releases/tag/v7.17.0) :tada:

**Pull request closed without merging**
