### PR TITLE
Allow inputAttributes.placeholder

### LINKED ISSUE #1274: inputAttributes: { placeholder: 'foo' } should work
## New feature motivation

If would be nice to provide the ability to set input placeholder in `inputAttributes` parameter:

```js
swal({
  input: 'tel',
  inputAttributes: {
    placeholder: '123-456-7890',
    pattern: '[0-9]{3}-[0-9]{3}-[0-9]{4}',
    required: true
  }
})
```

## Actual behavior

The code above produces the input with empty placeholder.

## Expected behavior

The input placeholder should be `123-456-7890`.

## Solution proposal

https://github.com/sweetalert2/sweetalert2/tree/fix/inputAttributes-placeholder

### PR DESCRIPTION
**Pull request by limonte**
Fixes #1274

### CODE REVIEW

**Comment by limonte** [comment]
@gverni would you mind to write a test case for this PR? If yes, that clone this PR, create a commit with a test case and push it. 

Suggestions: I personally find [GitHub Pull Requests in Visual Studio Code](https://code.visualstudio.com/blogs/2018/09/10/introducing-github-pullrequests) the easiest way to work with PRs.

**Comment by gverni** [comment]
Hi @limonte it's maybe an overshoot, but I was thinking to implement 3 test cases, one for `type="text"`, one for `type="textarea"`, and one for `type="file"` (just because they are handled in 3 different `case` statements). I've noticed that for `type="file"` the placeholder is correctly added to the `input ` tag but it's not shown (in chrome i can see only "No file chosen"). Obviously the test will still pass, but I was wondering if it makes sense to call the `setInputPlaceholder()` for `type="file"` if the user will not see it anyway.

**Comment by gverni** [comment]
Hi @limonte I created a new test file (`inputAttributes.js`) to add the 3 placeholder tests. In addition to that I added a specific test for the "legacy" `inputPlaceholder`  in the `input.js`. (I know there were already other tests using that configuratoin parameter, but I thought we should have a specific test). Let me know if you agree with this strategy or if it's an overshoot. 

P.S. I used the Check out PR feature of Visual Studio, and I've noticed this is adding a merge from the master branch as well. So when I pushed on this branch, it added that commit as well. If we squash the PR should not be a problem, but I'm not sure if there's a better way of doing that.

**Comment by limonte** [comment]
LGTM!

PS. you might want to reconfigure your Git settings to match the GitHub email, currently it doesn't:

**Comment by limonte** [comment]
> P.S. I used the Check out PR feature of Visual Studio, and I've noticed this is adding a merge from the master branch as well. So when I pushed on this branch, it added that commit as well. If we squash the PR should not be a problem, but I'm not sure if there's a better way of doing that.

Exactly, with squashing we don't really care about the commit history of a PR

**Pull request merged**
