### PR TITLE
Support date/datetime

### PR DESCRIPTION
**Pull request by alamin3000**

### CODE REVIEW

**Comment by limonte** [comment]
Thanks for the contribution @alamin3000, but due to the [poor browsers support](https://caniuse.com/#feat=input-datetime) I can't merge it. 

Here's the list of browsers we are supporting: https://github.com/sweetalert2/sweetalert2#browser-compatibility

Each feature should be supported equally or with appropriate fallback. We can't have features unsupported by some of the major browsers, in this case, Safari, IE11 and partially Firefox.

**Comment by alamin3000** [comment]
Poor browser support?! You do realize that this is HTML5 specification.  Whether browser support that or not has nothing to do with your lib supporting that browser.  Even Element UI library support 'date' and all other variants.  You should just simply passthrough whatever input type user choose to use.  

Anyway.  Just because of this I am using ElementUI MessageBox. http://element.eleme.io/#/en-US/component/message-box

**Comment by zenflow** [comment]
@limonte Why can't we support "using whatever input types are supported by the host browser environment"? If you look at it that way then it's not a feature that would be broken on IE, and it doesn't drag everyone (i.e developers for modern browsers) down to the level of IE11. 

If someone wants to use date/datetime inputs and target IE11 then they should load a polyfill. We could document this, but I don't think that's really necessary since we don't explicitly say what input types are supported, and one should naturally assume that input types not supported by the browser will not be magically made to work by SweetAlert2.

What do you think?

**Comment by alamin3000** [comment]
I had commented indicating that HTML5 input types has nothing to do with your library supporting IE11 or so on. Just like how ElementUI and other library simply passthrough the input type user wants to use. 
Anyway I updated the code support all other input types.  If you want me to change something or write differently let me know.  I used array because list is too big and it is easier to generate the error message.

**Comment by limonte** [comment]
> and one should naturally assume

This assumption is IMO incorrect, let's not underestimate people's stupidity. They will raise issues with questions similar to "Why `input: 'date'` doesn't work in IE11???".

I still think that we shouldn't support which are supported by limited browsers. It's much easier both for maintainers and users to be sure about the **equal support of all features** in all supported browsers.

If we'll make an exception then neither we are nor our users will be sure about the browser support of different features.

Let's not bring anything which will cause confusions, the front-end world is already fucked up, let's not make even more unstable and chaotic.

---

@alamin3000 for your project please the `html` parameter with any input you want:

```js
swal({
   html: '<input type="date">'
})
```

Personally, I think that this is a bad solution which will not work and therefore discriminate IE11 and Safari users.

Here's the good solution with the equal support in all supported browsers (flatpickr): https://jsfiddle.net/ad3quksn/1146/

**Comment by alamin3000** [comment]
> I still think that we shouldn't support features which are supported by limited browsers.

This isn't a feature _you_ need to support.  Your library isn't about html input controls.  It's an alert box... and you are letting people put any HTML5 input control there.  Anyway, I respect your opinion, but don't quite see your point/agrument and thus already moved on with different library.

**Comment by alamin3000** [comment]
Element UI.  I am only using individual MessageBox and Loading indicator components.  Their API for alert/prompt is very similar to yours.  but you **can** put 'date' in the inputValue field.  If browser doesn't support date than at worse they will see an textbox.  So it isn't like your library _won't work_ with IE11/Safari.  

http://element.eleme.io/#/en-US/component/message-box

**Comment by zenflow** [comment]
@limonte 

> This assumption is IMO incorrect, let's not underestimate people's stupidity. They will raise issues with questions similar to "Why input: 'date' doesn't work in IE11???".

I don't underestimate the stupidity of some people, but restricting functionality just so that these stupid people don't get confused makes **our library** stupid. What is the problem if stupid people post stupid questions like that? I would just close it saying "this isn't an issue with sweetalert2.. 'date' inputs are not supported in IE11" and adding a helpful suggestion "if you need to support IE11 use a date input polyfill or find another way to get dates from the user". I would not say it to them but it's really stupid to think SweetAlert2 uses it's own implementation of a 'date' input when it appears as a native date input, and really careless to use browser native 'date' inputs when they need to support IE11. We shouldn't make it our problem that there are people this stupid. 

> I still think that we shouldn't support features which are supported by limited browsers. It's much easier both for maintainers and users to be sure about the equal support of all features in all supported browsers.

Like @alamin3000 was trying to say: It's not really something to **support**, it's more like something we should not **prevent** by throwing an error when users pass `input: 'date'`, rather than just using it with the normal input behavior. It's the same as using `html: '<input type="date">'` .. this **also** will not work in IE11, but we allow users to do it.. Ignoring the logistical overhead and supposing it was possible, would you **want** to prevent users from passing HTML that doesn't behave the same in every browser?

> If we'll make an exception then neither we nor our users will be sure about the browser support of different features.

It would not be an exception. All of **our** features would still work in all browsers, but not all **browser** features will, same as always.

@limonte Would you feel better about this if instead defining every "valid" input type, we used the behavior for text/email/password/etc as the default, used when the `type` doesn't match one of the special cases? That way we avoid the need to tell our users what types of input they can or can not use.

**Comment by limonte** [comment]
SweetAlert2 + flatpickr datepicker recipe: https://sweetalert2.github.io/recipe-gallery/input-date-flatpickr.html

**Pull request closed without merging**
