### PR TITLE
Compliance Issue fixes

### PR DESCRIPTION
**Pull request by agonnade-cex**
"Fixed 

1. An img element must have an alt attribute, except under certain conditions 
2. label element with a for attribute must have an ID value that matches that for attribute

### CODE REVIEW

**Comment by parabameya** [comment]
This is Ameya Parab from Careexpand. We need this fix for the 508 Compliance for Medicare. If we can get this published sooner it will help us to launch it for our patients. 

Thanks

**Comment by parabameya** [comment]
@nixta  @pomartel  @sontan  Please review this request

**Review by parabameya — APPROVED** [review]

**Comment by limonte** [comment]
@parabameya you're blocked now for unnecessarily pinging unrelated people and putting pressure. I will review this PR soon.

**Pull request closed without merging**
