### PR TITLE
Polish types

### PR DESCRIPTION
**Pull request by limonte**
Before:

image

After:

image

### CODE REVIEW

**Comment by toverux** [comment]
Cool, but why remove the @links? In Webstorm I can click on the references tagged like that.

**Comment by limonte** [comment]
> Cool, but why remove the @links? In Webstorm I can click on the references tagged like that.

A-ha, Webstorm. VSCode doesn't support them and makes it harder to read: 

image

Considering the absolute dominance of VSCode, I'd rather improve the readability for them.

**Comment by toverux** [comment]
Ach! Yes, fair point - that would be really useful if we had a doc generator on a bigger library, but if that only degrades the experience of most users here, that's not interesting.

**Pull request merged**
