### PR TITLE
fix(types): add missing updatable parameters

### PR DESCRIPTION
**Pull request by rafaelss95**
This adds the missing updatable parameters

- `background`
- `iconColor`
- `preConfirm`
- `preDeny`

... added in #2054 and #2300 :)

### CODE REVIEW

**Comment by rafaelss95** [comment]
While doing this, I just noticed something that might be improved:

- `currentProgressStep` is currently `string`, however it seems that it should be `number` instead, as it corresponds to the index of the `step`;
- `progressStepsDistance` is currently `string`, however it seems that it should be `number | string` instead as it represents a `width` and `width` is `number | string`?
- `SweetAlertHideClass`, `SweetAlertShowClass` and `SweetAlertCustomClass`' members are currently `string`, however it seems that it should be `string | readonly string[]` as it support multiple classes.

Let me know your opinion on this, @limonte. So, if applicable, I can push a new commit here or create another one PR :)

**Review by limonte — APPROVED** [review]
Thank you @rafaelss95!

**Comment by limonte** [comment]
> While doing this, I just noticed something that might be improved:
> 
> * `currentProgressStep` is currently `string`, however it seems that it should be `number` instead as it represents to the index of the `step`;
> * `progressStepsDistance` is currently `string`, however it seems that it should be `number | string` instead as it represents a `width` and `width` is `number | string`?
> * `SweetAlertHideClass`, `SweetAlertShowClass` and `SweetAlertCustomClass`' members are currently `string`, however it seems that it should be `string | readonly string[]` as it support multiple classes.
> 
> Let me know your opinion on this, @limonte. So, if applicable, I can push a new commit here or create another one PR :)

I think it'd be easier to push to commit to this PR, thank you for these findings @rafaelss95!

**Review by limonte — APPROVED** [review]
Thank you @rafaelss95!

**Pull request merged**
