### PR TITLE
$10 PR 🤑 

### LINKED ISSUE #1948: Unable to click the confirm/cancel button of tall popup in iOS
## Current behavior

ezgif-2-fb1e4b30b117

Instead of button being clicked, the bottom panel appears. It'll be possible to click the button after additional scrolling.

## Expected behavior

Users should be able to click the button

### Live demo

https://sweetalert2.github.io/#long-text

### PR DESCRIPTION
**Pull request by tiagostutz**
I tested locally by placing the generated css build (`/dist/sweetalert2.css`) in sweetalert2.github.io and checked the examples. All was fine.

I'd like to know if there's an automated way to test CSS and UI changes or if you have any tip I must follow to see if the changes are all good.

closes #1948

### CODE REVIEW

**Comment by tiagostutz** [comment]
Not passing the lint validator. For more reference on `env` value on CSS:

https://bitsofco.de/css-environment-variables/

**Comment by limonte** [comment]
@tiagostutz thank you for the contribution, but I have to reject it for these reasons:

1. I didn't manage to see it, after cloning the PR and building there were no padding on `.swal2-actions` on my iPhone 7, not sure why
2. The padding is making popups look a bit "broken" with that big gap at the bottom of popups
3. The approach doesn't distinguish small and tall popups, small popups will be "uglyfied" with the bottom padding without any reasons for doing that.

I just made another PR with the JS approach, @tiagostutz and @gverni your review would be very welcome!

**Comment by limonte** [comment]
Hey @tiagostutz! Just wanted to say thank you for your support for a couple of months! I appreciate it!

**Comment by tiagostutz** [comment]
> Hey @tiagostutz! Just wanted to say thank you for your support for a couple of months! I appreciate it!

Hi @limonte ! 👋

Sure and I'm keeping it up for more couple of months and years.!
(BTW thanks for "pinging" me, GitHub didnt notified me about my Paypal problem)

Good job you have been doing here. If you need any help with some issues you think I can tackle, please let me know.!

**Comment by limonte** [comment]
Thank you @tiagostutz 

If you didn't mean to cancel your subscription I guess I need to revert https://github.com/sweetalert2/sweetalert2/commit/f56e014a1434f6c52009c80b9905cc0a3186f0e9 

Apologies about being too hasty! As well as you I wasn't expecting GitHub to fail with notifying sponsors about the issues with the payment method. Therefore I thought that you've cancelled your sponsorship.

Thank you for the kind words about my work. I appreciate it a lot and will continue to keep the plugin great! And sure, I'll ping you in cases there will be something interesting to handle! Thanks!

**Comment by tiagostutz** [comment]
> Thank you @tiagostutz
> 
> If you didn't mean to cancel your subscription I guess I need to revert [f56e014](https://github.com/sweetalert2/sweetalert2/commit/f56e014a1434f6c52009c80b9905cc0a3186f0e9) Apologies about being too hasty! As well as you I wasn't expecting GitHub to fail with notifying sponsors about the issues with the payment method. Therefore I thought that you've cancelled your sponsorship.
> 
> Thank you for the kind words about my work. I appreciate it a lot and will continue to keep the plugin great! And sure, I'll ping you in cases there will be something interesting to handle! Thanks!

Yeah, I didn't mean to cancel at all... no need to apolgize, I understand perfectly.!
Indeed, that was really weird that GitHub didn't notify me about that issue. But now everything is OK.

Thanks a lot!

**Comment by limonte** [comment]
@tiagostutz Will do 👍 

I guess you need to re-enable sponsorship because the previous one was automatically cancelled by GitHub.

**Comment by tiagostutz** [comment]
Indeed! Just re-enabled it. Thanks!!

**Pull request closed without merging**
