### PR TITLE
fix(types): remove the readonly modifier from 'SweetAlertOptions'

### PR DESCRIPTION
**Pull request by rafaelss95**
Fixes https://github.com/sweetalert2/sweetalert2/pull/1983#issuecomment-640288808

### CODE REVIEW

**Comment by rafaelss95** [comment]
@limonte @toverux can I add the readonly modifier for the **non** updatable parameters?

**Comment by limonte** [comment]
> Is it outdated, right? Because I can't update preConfirm via `update`...

It's this one: https://github.com/sweetalert2/sweetalert2/issues/1778

**Comment by rafaelss95** [comment]
> > Is it outdated, right? Because I can't update preConfirm via `update`...
> 
> No, it's not outdated. It's this one: #1778

Ahhh, got it!! :)

**Comment by limonte** [comment]
> @limonte @toverux can I add the readonly modifier for the **non** updatable parameters?

I don't have any opinion here, but if you think that should be done please go ahead with the PR, I'd be happy to review it!

**Pull request merged**
