### PR TITLE
Reduce method complexity of setParameters()

### LINKED ISSUE #1490: Fix "method_complexity" issue in src/utils/setParameters.js
Function `setParameters` has a Cognitive Complexity of 13 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/sweetalert2/sweetalert2/src/utils/setParameters.js#issue_5c9a2e86cf875d000100006b

### PR DESCRIPTION
**Pull request by gverni**
Created two functions:
* `setDefaultInputValidators()`: to assign default input  validators
* `validateCustomTargetElement()`: to check if the target element is a valid one

Also:
* Moved warning message to a constant outside of function
* Code clean-up

Fix #1490

### CODE REVIEW

**Comment by gverni** [comment]
Codeclimate integration reports  only 1 issue fixed ("Function setParameters has 34 lines of code (exceeds 25 allowed). Consider refactoring."). I'm checking about method complexity.

**Comment by gverni** [comment]
In 8e989d2 I removed the if statement at the end of the `setParameters()` function. The reason is that the condition:

https://github.com/sweetalert2/sweetalert2/blob/801edf07867c5a15955f31dcabb67aca0813bd04/src/utils/setParameters.js#L54-L56

**always returned `true`** (or I didn't understand the logic). In fact `oldPopup.parentNode` is the Swal2 container (i.e. `swal2-container`). The only condition when this condition is true is if the `targetElement` is actually the popup itself.... which is a use case I cannot think of. 

Replacing the right side of the OR with a more correct: 

`oldPopup.parentNode.parentNode !== targetElement`

makes 11 test fail: 

  ✗ toast aria attributes
  ✗ grow fullscreen
  ✗ Modal positions
  ✗ Toast positions
  ✗ Toast positions with target
  ✗ should throw console error about invalid type
  ✗ container should have .swal2-rtl in case of <body dir="rtl">
  ✗ container should have .swal2-rtl in case of <body style="direction: rtl">
  ✗ should show the popup with OK button in case of empty object passed as an argument
  ✗ JS element as html param
  ✗ onBeforeOpen

I can analyze why the above fails (likely cause is that the `dom` is not updated unless the target element is different), but before doing so, @limonte @zenflow do you agree with my analysis that that condition is always `true`? Or is there some obscure use case that I cannot think of that needs that check?

**Comment by limonte** [comment]
Thank you @gverni!

I reverted the `loaderOnConfirmMessage` variable, other than that all is good :rocket:

**Pull request merged**
