### PR TITLE
fix: toast pop up sizing based on message length

### PR DESCRIPTION
**Pull request by mani91g**
code fix to resolve toast pop up width based on message size

PR is fix for issue [#2366](https://github.com/sweetalert2/sweetalert2/issues/2366)

### CODE REVIEW

**Comment by limonte** [comment]
This will break other toasts:

compare the preview of this PR: https://deploy-preview-2540--sweetalert2.netlify.app/#mixin

CleanShot 2022-10-28 at 14 33 58@2x

and the current version: https://sweetalert2.github.io/#mixin

CleanShot 2022-10-28 at 14 33 33@2x

**Comment by mani91g** [comment]
> This will break other toasts:
> 
> compare the preview of this PR: https://deploy-preview-2540--sweetalert2.netlify.app/#mixin
> 
> CleanShot 2022-10-28 at 14 33 58@2x
> 
> and the current version: https://sweetalert2.github.io/#mixin
> 
> CleanShot 2022-10-28 at 14 33 33@2x

I have made another change and I manually checked the deployed version against the actual. All seems to be ok now.

**Comment by limonte** [comment]
now on preview this code

```js
Swal.fire({toast: true, title: 'hello' , showConfirmButton: false, width: 'auto', showCloseButton: true})
```

produces this:

CleanShot 2022-10-28 at 22 03 49@2x

instead of expected

CleanShot 2022-10-28 at 22 06 10@2x

**Comment by limonte** [comment]
`grid-template-columns` should probably be `0 auto 1fr` by default and `1fr auto 1fr` when `.swal2-toast` has also `[class^=swal2-icon]`

**Comment by limonte** [comment]
Thank you @mani91g 👏

**Comment by mani91g** [comment]
You are most welcome @limonte . This was my first ever oss contribution and it was very satisfying one :)

**Comment by kukafeippp** [comment]
IOS系统BUG,使用插件弹窗闪退
[PC端：](https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxgetvideo?msgid=3845882206220183307&skey=%40crypt_6f7a73df_16d7e95a3ccffe419fc01b19dafc0975)
[IOS端：](https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxgetvideo?msgid=192712378397939575&skey=%40crypt_6f7a73df_16d7e95a3ccffe419fc01b19dafc0975)

<script src="../js/jquery-3.6.1.min.js"></script>
<script src="../js/sweetalert2.min.js"></script>
<link href="../css/sweetalert2.min.css" rel="stylesheet" />
<asp:Button ID="Button1" runat="server" BorderStyle="None" Font-Size="15px" Text="loading直接JS，功能测试" OnClientClick="MyAutoRun()" Width="80%" BackColor="#72C76C" ForeColor="White" Height="30px" />
       <script language="javascript">  //这里是提交申请的loading的等待动画
                function MyAutoRun() {
                    Swal.fire({
                        text: '正在创建工单，请稍候......',
                        imageUrl: '/tubiaoimg/loading.gif',
                        imageWidth: 400,
                        //imageHeight: 200,
                        showConfirmButton: false, //是否显示“Confirm（确认）”按钮。
                        allowOutsideClick: false //是否允许点击对话框外部来关闭对话框。
                    })
                }
            </script>

后台代码：
    Protected Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim a As Integer = 0
        For a = 1 To 100000000
            a += 0.00000000001
        Next
        js = "Swal.fire('成功!', '已计算了" & a - 1 & "次！', 'success');"  'success 对号，error 错号，question 问号，warning 黄叹号，info 蓝叹号
        ClientScript.RegisterStartupScript(Page.[GetType](), Guid.NewGuid().ToString(), js, True)
    End Sub

**Comment by limonte** [comment]
@kukafei2123 please create another issue since it's unrelating to this thread, in your issue please follow the issue template.

**Pull request merged**
