### PR TITLE
Add closeButtonHtml param

### LINKED ISSUE #1663: Request: Provide option to change icon close modal
swal-option-to-chage-close-icon

UI/UX might design a fancy close icon on top-right or top-left in svg or png format. Sometimes, we would need to replace the default icon with any type of font icon (fontawesome, ...). Real example:

new-svg-close-icon

I suggest to add one more option named as `closeIcon` or `closeIconPath` or `closeIconHtml` to allow developer override the default icon with HTML code. For example:

`<i class="fas fa-times"></i>` or `<i class="icon icon-close-circle"></i>` or `<svg>...</svg>`

Currently, I used the `html` as the workaround to override the close icon. However, it is not such a nice code because we have to write some codes in `onBeforeOpen` function.

### PR DESCRIPTION
**Pull request by limonte**
Closes #1663

Docs: https://github.com/sweetalert2/sweetalert2.github.io/pull/93

### CODE REVIEW

**Comment by gverni** [comment]
LGTM. Tried with `font-awesome` and SVG and it works fine.

**Comment by gverni** [comment]
@limonte just added a test case. Hope you don't mind...

**Comment by limonte** [comment]
> @limonte just added a test case. Hope you don't mind...

How can I mind someone correcting my laziness :D Thank you @gverni!!

You know better than me that "if it's not tested, it's broken (c)"

**Pull request merged**
