### PR TITLE
fix: set babel browser targets to default targets

### PR DESCRIPTION
**Pull request by ehoogeveen-medweb**
Closes https://github.com/sweetalert2/sweetalert2/issues/2758.

For reference: `defaults` means `> 0.5%, last 2 versions, Firefox ESR, not dead` [according to browserslist](https://github.com/browserslist/browserslist?tab=readme-ov-file#full-list) (which is what `babel` uses). So that means:
* Every version with more than 0.5% usage globally
* The most recent 2 versions of every browser
* The current Firefox ESR
* But *excluding* browsers that are considered dead, e.g. Internet Explorer

You can see the current targets by running `yarn browserslist "defaults"` (or `npx browserslist "defaults"` or similar). The data it uses for queries like `last 2 versions` and `Firefox ESR` is based on the `caniuse-lite` dependency, see [here](https://github.com/browserslist/browserslist?tab=readme-ov-file#update-caniuse-lite) for how to update it / keep it updated (I'm not entirely sure how this works with `yarn.lock`).

## Summary by CodeRabbit

- **New Features**
	- Enhanced compatibility across various environments by updating the JavaScript compilation settings.
  
- **Bug Fixes**
	- Improved performance and adherence to standards in the bundled JavaScript output.

### CODE REVIEW

**Comment by limonte** [comment]
Thanks a lot @ehoogeveen-medweb! ❤️

**Review by limonte — APPROVED** [review]

**Comment by limonte** [comment]
related commit: https://github.com/sweetalert2/sweetalert2/commit/d97d9b81cf5b3e714811a195b0897e5712a4e429

**Comment by ehoogeveen-medweb** [comment]
If it's specifically those two, I think we can also do this:
```
    babel({
      babelHelpers: 'bundled',
      presets: [
        [
          '@babel/preset-env',
          { include: ['transform-optional-chaining', 'transform-class-properties'] },
        ],
      ],
      targets: 'defaults',
    }),
```

**Comment by limonte** [comment]
oh, that's better, thanks

**Comment by limonte** [comment]
good that I've added that test for webpack 4 a while ago 😊

**Comment by limonte** [comment]
CleanShot 2024-09-04 at 15 18 21@2x

-10%!

Nice improvement, thanks again @ehoogeveen-medweb for your contribution!

**Comment by ehoogeveen-medweb** [comment]
My pleasure!

**Pull request merged**
