### PR TITLE
Add protestware notice

### PR DESCRIPTION
**Pull request by limonte**
CleanShot 2022-11-24 at 13 47 29@2x

### CODE REVIEW

**Comment by iurok106** [comment]
cringe

**Comment by flexagoon** [comment]
Yeah breaking a javascript popup library for russian sites will definitely make putin stop the war huh

**Comment by limonte** [comment]
The collapse of the regime will make him stop. The regime is a complex thing and it includes websites of course. I definitely added some tiny cracks to runet and therefore to the regime.

You guys seem so powerless and helpless there. Everybody can contribute to regime fall. I definitely did my part.

**Pull request merged**
