### PR TITLE
Reduced complexity of renderActions()

### LINKED ISSUE #1489: Fix "method_complexity" issue in src/utils/dom/renderers/renderActions.js
Function `renderActions` has a Cognitive Complexity of 11 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/sweetalert2/sweetalert2/src/utils/dom/renderers/renderActions.js#issue_5c9a2e86cf875d000100006f

### PR DESCRIPTION
**Pull request by gverni**
Created two functions
* `renderButton()`: generic function to apply rendering parameters to buttons
* `handleButtonsStyling()`: function  to apply additional styling to buttons (if `params.buttonsStyling` is truthy)

Closes #1489

### CODE REVIEW

**Comment by gverni** [comment]
> Code Climate has analyzed commit [c873297](https://github.com/sweetalert2/sweetalert2/commit/c8732972930bb5938064ce1efceb14bbbbf003c6) and detected **2 issues** on this pull request.

I think codeclimate has been a bit _picky_ here. I do agree we called `renderButton()` twice, but even though the arguments may look similar, they are actually quite different (confirm vs cancel button). Apart from using an array (which IMHO would make the code less readable) or changing the name of the swal parameters (breaking change) I don't see much scope to solve this one. 

@limonte what do you think?

**Comment by gverni** [comment]
Bundlesize decreased to +26B with https://github.com/sweetalert2/sweetalert2/pull/1523/commits/927d84c382f3c7c2008246fe5e9b166e1745bcf9. I'll work to reduce it further...

**Comment by limonte** [comment]
This is much better, good work @gverni! 

Robots are happy and I'm happy, feel free to merge when you're done :rocket:

**Comment by gverni** [comment]
I've done some check on the size since bundlesize still report +26B with the latest commit. 

Commit 40818d85682fd23cbed70e6380b759646eec66ed (base for my branch)
* min.js size: 65075
* gzip size: 15735

Commit e162e53b670a120bd3f1cae74c7653d5855c7674 (this PR)
* min.js file size: 64952 (-123B)
* gzip size: 15756 (+21)

The gzip bundle has been obtained using the macOS `gzip` util with no parameters. 
So it looks like we reduce the min file size, but we actually increased the gzip size.

**Comment by limonte** [comment]
> So it looks like we reduce the min file size, but we actually increased the gzip size.

Interesting observation! I never faced that before but it is probably possible.

**Pull request merged**
