### PR TITLE
Consistent hook names

### PR DESCRIPTION
**Pull request by toverux**
As discussed in #2055.

Hooks were previously named as follows:

| Before hook | After hook |
|-------------|------------|
| onBeforeOpen  | onOpen       |
|             | onRender     |
| onClose       | onAfterClose |
|             | onDestroy    |

All have been deprecated and renamed according to the convention used by frameworks like UIKit or React:

| Before hook | After hook |
|-------------|------------|
| willOpen  | didOpen       |
|             | didRender     |
| willClose       | didClose |
|             | didDestroy    |

- Old hooks are still called if defined, **but only if the new name is not used simultaneously**,
- .d.ts doc blocks for the new hooks have been improved,
- Old hooks are still present in the .d.ts file but have been marked as `@deprecated`, and a warning is printed if they're used in runtime.

### CODE REVIEW

**Review by limonte — CHANGES_REQUESTED** [review]
Looks great!

One thing before merging is to resolve three small CodeClimate issues by extracting new code into small functions

**Comment by limonte** [comment]
@toverux just to confirm, this PR will resolve your issues with https://github.com/sweetalert2/ngx-sweetalert2/issues/173#issuecomment-694538277 right?

**Comment by toverux** [comment]
Yes !

**Comment by limonte** [comment]
> 
> 
> Yes !

@toverux great! Let me know if you have time today for those small refactorings, if not then I'll merge the PR and fix them by myself so you can proceed with changes in `ngx-sweetalert2`

**Comment by toverux** [comment]
Indeed, unfortunately I won't be able to look at this today, but there's no hurry if you wanna fix it before merging, I won't be able to update ngx-sweetalert2 before tomorrow evening at least!

**Review by limonte — APPROVED** [review]
Thank you @toverux!

**Comment by toverux** [comment]
Yay! thanks!

**Pull request merged**
