### PR TITLE
Add ability to pass function as a template param

### LINKED ISSUE #2518: Ability to pass functions in template params
For the note 3, I thought to:
1. [Parse function from string ](https://stackoverflow.com/a/28011280/13672469), of course there are grammar (apparently arrow function are not working, but but I didn't do any test, I prefer the proposal `new Function("return " + "function (a, b) { return a + b; }")();`, where only the last string is the last string that is the one to put as the value of the `<swal-param>` tag), but why not? 
2. Don't forget to assign function type in `const defaultParams `

_Originally posted by @plouf142 in https://github.com/sweetalert2/sweetalert2/issues/2515#issuecomment-1271224247_

### PR DESCRIPTION
**Pull request by limonte**
closes #2518

here's how it'll work:

```html
<template id="my-swal">
  <swal-title>Function param</swal-title>
  <swal-param name="input" value="text"></swal-param>
  <swal-function-param name="didOpen" value="modal => console.log(modal)"></swal-function-param>
</template>
```

### CODE REVIEW

**Comment by limonte** [comment]
@plouf142 let me know what you think about this PR, thanks! 

The preview is available here: https://deploy-preview-2519--sweetalert2.netlify.app/ you can test out the new feature in console.

**Comment by plouf142** [comment]
It's working fine! 

The PR has'nt get user documentation modification, but I think it's the next step.

**Comment by limonte** [comment]
> It's working fine!
> 
> The PR has'nt get user documentation modification, but I think it's the next step.

Yup, it's a separate repo: https://github.com/sweetalert2/sweetalert2.github.io

**Comment by limonte** [comment]
Usage example added: https://sweetalert2.github.io/#declarative-templates

**Pull request merged**
