### PR TITLE
Deprecate enableConfirmButton() and disableConfirmButton()

### LINKED ISSUE #1496: Should we deprecate enableConfirmButton()/disableConfirmButton()?
These legacy methods were here before `Swal.getConfirmButton()` was added.

Since devs can enable/disable the Confirm button as simple as:

```js
Swal.getConfirmButton().setAttribute('disabled', '')
Swal.getConfirmButton().removeAttribute('disabled')
```

I don't think there's a need for additional complexity in API.

@gverni what do you think?

### PR DESCRIPTION
**Pull request by limonte**
Closes #1496

### CODE REVIEW

**Comment by gverni** [comment]
@limonte I've done a quick and dirty script to check how did we get to go beyond 15k with the bundle. Find below the results. To check the size I've used the `content-length` value of the response header from `cdn.jsdelivr.net`. 

```
Version: Size (Diff from prev version)
v7.30.0: 15393 (15393)
v7.31.0: 15469 (76)
v7.31.1: 15492 (23)
v7.32.0: 15516 (24)
v7.32.1: 15527 (11)
v7.32.2: 15528 (1)
v7.32.4: 15497 (-31)
v7.33.0: 15512 (15)
v7.33.1: 15512 (0)
v8.0.0: 14847 (-665)
v8.0.1: 14847 (0)
v8.0.2: 14847 (0)
v8.0.3: 14850 (3)
v8.0.4: 14851 (1)
v8.0.5: 14850 (-1)
v8.0.6: 14852 (2)
v8.0.7: 14853 (1)
v8.1.0: 14841 (-12)
v8.2.0: 14857 (16)
v8.2.1: 14890 (33)
v8.2.2: 14913 (23)
v8.2.3: 14920 (7)
v8.2.4: 14921 (1)
v8.2.5: 14927 (6)
v8.2.6: 14929 (2)
v8.3.0: 15090 (161)
v8.4.0: 15134 (44)
v8.5.0: 15176 (42)
v8.6.0: 15222 (46)
v8.7.0: 15342 (120)
```

From what I see, v8.3.0 and 8.70 seem to have added quite a lot. But we are still below the latest version on 7.x branch.

**Comment by limonte** [comment]
Thank you @gverni that you're tracking the bundle size, would you mind to share that quick and dirty script? :) The diff part is very helpful. I'm using https://bundlephobia.com/ sometimes, but they do not provide diffs.

**Comment by limonte** [comment]
Or, if you have some spare time create the npm CLI tool. The `bundlesize-history` name is free :)

I would expect something like:

```sh
bundlesize-history --package-name sweetalert2 --start-from 7.0.0
```

Related article: https://blog.developer.atlassian.com/scripting-with-node/

**Comment by gverni** [comment]
@limonte find my script here: 

https://gist.github.com/gverni/9a3bab7b83469af71566e27f4f16a1e2

It's a mix of GitHub APIs and simple fetch to `cdn.jsdelivr.net`. You need the `node-fetch` in order to use it. 

 > Or, if you have some spare time create the npm CLI tool. The bundlesize-history name is free :)

That's an very tempting idea....

**Comment by Herz3h** [comment]
Whats the replacement functions/method to disable/enable confirm button ?

**Comment by limonte** [comment]
> Whats the replacement functions/method to disable/enable confirm button ?

- `Swal.getConfirmButton().setAttribute('disabled', '')`
- `Swal.getConfirmButton().removeAttribute('disabled')`

**Pull request merged**
