### PR TITLE
chore: convert to es6 class

### LINKED ISSUE #1950: Convert to ES6 class
https://github.com/sweetalert2/sweetalert2/blob/master/src/SweetAlert.js

### PR DESCRIPTION
**Pull request by limonte**
Closes #1950

### CODE REVIEW

**Comment by limonte** [comment]
@gverni this PR resolved the last issue from codeclmate you were trying to resolve in #1632

image

:tada:

**Comment by nainardev** [comment]
What's code smell?

**Comment by limonte** [comment]
> What's code smell?

http://letmegooglethat.com/?q=code+smell

**Comment by nainardev** [comment]
🤣

**Pull request merged**
